library(shiny)
library(shinydashboard)
library(ggplot2)
library(lubridate)
library(DT)
library(jpeg)
library(grid)
library(leaflet)
library(scales)

allstations <- c('Jefferson_Park.csv', 'Cermak-Chinatown.csv', 'Central-Lake.csv', 'Dempster-Skokie.csv', 'Dempster.csv', 'Lake__State.csv', 'Oak_Park-Forest_Park.csv', 'Kedzie-Homan-Forest_Park.csv', '35th__Archer.csv', 'Addison-North_Main.csv', 'Main.csv', 'Chicago__State.csv', 'Wellington.csv', 'Austin-Forest_Park.csv', 'Clinton-Lake.csv', 'East_63rd-Cottage_Grove.csv', 'Grand__State.csv', 'Wilson.csv', 'Cicero-Cermak.csv', 'State__Lake.csv', '51st.csv', '95th__Dan_Ryan.csv', 'Jackson__State.csv', 'Randolph__Wabash.csv', 'Logan_Square.csv', 'Morse.csv', 'Grand__Milwaukee.csv', '69th.csv', 'Paulina.csv', 'Damen-Brown.csv', 'Washington__Dearborn.csv', 'Kimball.csv', 'Clark__Lake.csv', 'Lawrence.csv', 'Polk.csv', '47th-Dan_Ryan.csv', 'Sedgwick.csv', '54th__Cermak.csv', 'Ashland__63rd.csv', 'Morgan-Lake.csv', 'Harrison.csv', 'Sheridan.csv', 'Racine.csv', 'Washington__Wells.csv', 'Quincy__Wells.csv', 'Foster.csv', 'California__Milwaukee.csv', 'Cermak-McCormick_Place.csv', 'Sox-35th-Dan_Ryan.csv', 'Chicago__Milwaukee.csv', "O'Hare_Airport.csv", 'Kedzie-Lake.csv', 'Fullerton.csv', 'Irving_Park-Brown.csv', 'LaSalle__Van_Buren.csv', 'Belmont-North_Main.csv', '79th.csv', 'Adams__Wabash.csv', 'Western-Orange.csv', 'Clinton-Forest_Park.csv', 'UIC-Halsted.csv', '35-Bronzeville-IIT.csv', '87th.csv', '18th.csv', 'Indiana.csv', 'Monroe__State.csv', "Irving_Park-O'Hare.csv", 'Cumberland.csv', 'Roosevelt.csv', 'Damen__Milwaukee.csv', 'Kedzie-Midway.csv', '63rd-Dan_Ryan.csv', 'Kedzie-Cermak.csv', 'Addison-Brown.csv', 'Division__Milwaukee.csv', 'Damen-Cermak.csv', 'Cicero-Lake.csv', 'Madison__Wabash.csv', 'Harlem-Lake.csv', 'Pulaski-Cermak.csv', 'Kedzie-Brown.csv', 'Central_Park.csv', "Harlem-O'Hare.csv", 'Chicago__Franklin.csv', 'North__Clybourn.csv', 'Berwyn.csv', 'Laramie.csv', 'Howard.csv', 'Granville.csv', 'Western-Forest_Park.csv', 'California-Cermak.csv', 'Ridgeland.csv', 'Western-Cermak.csv', 'Halsted__63rd.csv', 'Pulaski-Forest_Park.csv', 'Montrose-Brown.csv', 'Linden.csv', 'Pulaski-Lake.csv', 'Harlem-Forest_Park.csv', 'Ashland-Orange.csv', 'Garfield-Dan_Ryan.csv', 'Halsted-Orange.csv', "Addison-O'Hare.csv", 'Pulaski-Orange.csv', 'Noyes.csv', '47th-South_Elevated.csv', 'Merchandise_Mart.csv', 'Midway_Airport.csv', '43rd.csv', 'Western__Milwaukee.csv', 'Ashland-Lake.csv', "Belmont-O'Hare.csv", 'Oak_Park-Lake.csv', 'Conservatory.csv', 'Library.csv', 'Loyola.csv', 'Southport.csv', "Montrose-O'Hare.csv", 'Jarvis.csv', 'South_Boulevard.csv', 'Cicero-Forest_Park.csv', 'Medical_Center.csv', 'Davis.csv', 'Clark__Division.csv', 'Jackson__Dearborn.csv', 'Washington__Wabash.csv', 'Francisco.csv', 'Central-Evanston.csv', 'Oakton-Skokie.csv', 'Austin-Lake.csv', 'Bryn_Mawr.csv', 'Kostner.csv', 'Forest_Park.csv', 'California-Lake.csv', 'Garfield-South_Elevated.csv', 'Rockwell.csv', 'Diversey.csv', 'Argyle.csv', 'LaSalle.csv', 'Monroe__Dearborn.csv', 'Rosemont.csv', 'King_Drive.csv', 'Armitage.csv', 'Thorndale.csv', 'Western-Brown.csv', 'Skokie.csv', 'Washington__State.csv', 'Homan.csv')
s_Jefferson_Park<-read.csv(file = "data/Jefferson_Park.csv")
s_Cermak___Chinatown<-read.csv(file = "data/Cermak-Chinatown.csv")
s_Central___Lake<-read.csv(file = "data/Central-Lake.csv")
s_Dempster___Skokie<-read.csv(file = "data/Dempster-Skokie.csv")
s_Dempster<-read.csv(file = "data/Dempster.csv")
s_Lake__State<-read.csv(file = "data/Lake__State.csv")
s_Oak_Park___Forest_Park<-read.csv(file = "data/Oak_Park-Forest_Park.csv")
s_Kedzie___Homan___Forest_Park<-read.csv(file = "data/Kedzie-Homan-Forest_Park.csv")
s_35th__Archer<-read.csv(file = "data/35th__Archer.csv")
s_Addison___North_Main<-read.csv(file = "data/Addison-North_Main.csv")
s_Main<-read.csv(file = "data/Main.csv")
s_Chicago__State<-read.csv(file = "data/Chicago__State.csv")
s_Wellington<-read.csv(file = "data/Wellington.csv")
s_Austin___Forest_Park<-read.csv(file = "data/Austin-Forest_Park.csv")
s_Clinton___Lake<-read.csv(file = "data/Clinton-Lake.csv")
s_East_63rd___Cottage_Grove<-read.csv(file = "data/East_63rd-Cottage_Grove.csv")
s_Grand__State<-read.csv(file = "data/Grand__State.csv")
s_Wilson<-read.csv(file = "data/Wilson.csv")
s_Cicero___Cermak<-read.csv(file = "data/Cicero-Cermak.csv")
s_State__Lake<-read.csv(file = "data/State__Lake.csv")
s_51st<-read.csv(file = "data/51st.csv")
s_95th__Dan_Ryan<-read.csv(file = "data/95th__Dan_Ryan.csv")
s_Jackson__State<-read.csv(file = "data/Jackson__State.csv")
s_Randolph__Wabash<-read.csv(file = "data/Randolph__Wabash.csv")
s_Logan_Square<-read.csv(file = "data/Logan_Square.csv")
s_Morse<-read.csv(file = "data/Morse.csv")
s_Grand__Milwaukee<-read.csv(file = "data/Grand__Milwaukee.csv")
s_69th<-read.csv(file = "data/69th.csv")
s_Paulina<-read.csv(file = "data/Paulina.csv")
s_Damen___Brown<-read.csv(file = "data/Damen-Brown.csv")
s_Washington__Dearborn<-read.csv(file = "data/Washington__Dearborn.csv")
s_Kimball<-read.csv(file = "data/Kimball.csv")
s_Clark__Lake<-read.csv(file = "data/Clark__Lake.csv")
s_Lawrence<-read.csv(file = "data/Lawrence.csv")
s_Polk<-read.csv(file = "data/Polk.csv")
s_47th___Dan_Ryan<-read.csv(file = "data/47th-Dan_Ryan.csv")
s_Sedgwick<-read.csv(file = "data/Sedgwick.csv")
s_54th__Cermak<-read.csv(file = "data/54th__Cermak.csv")
s_Ashland__63rd<-read.csv(file = "data/Ashland__63rd.csv")
s_Morgan___Lake<-read.csv(file = "data/Morgan-Lake.csv")
s_Harrison<-read.csv(file = "data/Harrison.csv")
s_Sheridan<-read.csv(file = "data/Sheridan.csv")
s_Racine<-read.csv(file = "data/Racine.csv")
s_Washington__Wells<-read.csv(file = "data/Washington__Wells.csv")
s_Quincy__Wells<-read.csv(file = "data/Quincy__Wells.csv")
s_Foster<-read.csv(file = "data/Foster.csv")
s_California__Milwaukee<-read.csv(file = "data/California__Milwaukee.csv")
s_Cermak___McCormick_Place<-read.csv(file = "data/Cermak-McCormick_Place.csv")
s_Sox___35th___Dan_Ryan<-read.csv(file = "data/Sox-35th-Dan_Ryan.csv")
s_Chicago__Milwaukee<-read.csv(file = "data/Chicago__Milwaukee.csv")
s_OHare_Airport<-read.csv(file = "data/O'Hare_Airport.csv")
s_Kedzie___Lake<-read.csv(file = "data/Kedzie-Lake.csv")
s_Fullerton<-read.csv(file = "data/Fullerton.csv")
s_Irving_Park___Brown<-read.csv(file = "data/Irving_Park-Brown.csv")
s_LaSalle__Van_Buren<-read.csv(file = "data/LaSalle__Van_Buren.csv")
s_Belmont___North_Main<-read.csv(file = "data/Belmont-North_Main.csv")
s_79th<-read.csv(file = "data/79th.csv")
s_Adams__Wabash<-read.csv(file = "data/Adams__Wabash.csv")
s_Western___Orange<-read.csv(file = "data/Western-Orange.csv")
s_Clinton___Forest_Park<-read.csv(file = "data/Clinton-Forest_Park.csv")
s_UIC___Halsted<-read.csv(file = "data/UIC-Halsted.csv")
s_35___Bronzeville___IIT<-read.csv(file = "data/35-Bronzeville-IIT.csv")
s_87th<-read.csv(file = "data/87th.csv")
s_18th<-read.csv(file = "data/18th.csv")
s_Indiana<-read.csv(file = "data/Indiana.csv")
s_Monroe__State<-read.csv(file = "data/Monroe__State.csv")
s_Irving_Park___OHare<-read.csv(file = "data/Irving_Park-O'Hare.csv")
s_Cumberland<-read.csv(file = "data/Cumberland.csv")
s_Roosevelt<-read.csv(file = "data/Roosevelt.csv")
s_Damen__Milwaukee<-read.csv(file = "data/Damen__Milwaukee.csv")
s_Kedzie___Midway<-read.csv(file = "data/Kedzie-Midway.csv")
s_63rd___Dan_Ryan<-read.csv(file = "data/63rd-Dan_Ryan.csv")
s_Kedzie___Cermak<-read.csv(file = "data/Kedzie-Cermak.csv")
s_Addison___Brown<-read.csv(file = "data/Addison-Brown.csv")
s_Division__Milwaukee<-read.csv(file = "data/Division__Milwaukee.csv")
s_Damen___Cermak<-read.csv(file = "data/Damen-Cermak.csv")
s_Cicero___Lake<-read.csv(file = "data/Cicero-Lake.csv")
s_Madison__Wabash<-read.csv(file = "data/Madison__Wabash.csv")
s_Harlem___Lake<-read.csv(file = "data/Harlem-Lake.csv")
s_Pulaski___Cermak<-read.csv(file = "data/Pulaski-Cermak.csv")
s_Kedzie___Brown<-read.csv(file = "data/Kedzie-Brown.csv")
s_Central_Park<-read.csv(file = "data/Central_Park.csv")
s_Harlem___OHare<-read.csv(file = "data/Harlem-O'Hare.csv")
s_Chicago__Franklin<-read.csv(file = "data/Chicago__Franklin.csv")
s_North__Clybourn<-read.csv(file = "data/North__Clybourn.csv")
s_Berwyn<-read.csv(file = "data/Berwyn.csv")
s_Laramie<-read.csv(file = "data/Laramie.csv")
s_Howard<-read.csv(file = "data/Howard.csv")
s_Granville<-read.csv(file = "data/Granville.csv")
s_Western___Forest_Park<-read.csv(file = "data/Western-Forest_Park.csv")
s_California___Cermak<-read.csv(file = "data/California-Cermak.csv")
s_Ridgeland<-read.csv(file = "data/Ridgeland.csv")
s_Western___Cermak<-read.csv(file = "data/Western-Cermak.csv")
s_Halsted__63rd<-read.csv(file = "data/Halsted__63rd.csv")
s_Pulaski___Forest_Park<-read.csv(file = "data/Pulaski-Forest_Park.csv")
s_Montrose___Brown<-read.csv(file = "data/Montrose-Brown.csv")
s_Linden<-read.csv(file = "data/Linden.csv")
s_Pulaski___Lake<-read.csv(file = "data/Pulaski-Lake.csv")
s_Harlem___Forest_Park<-read.csv(file = "data/Harlem-Forest_Park.csv")
s_Ashland___Orange<-read.csv(file = "data/Ashland-Orange.csv")
s_Garfield___Dan_Ryan<-read.csv(file = "data/Garfield-Dan_Ryan.csv")
s_Halsted___Orange<-read.csv(file = "data/Halsted-Orange.csv")
s_Addison___OHare<-read.csv(file = "data/Addison-O'Hare.csv")
s_Pulaski___Orange<-read.csv(file = "data/Pulaski-Orange.csv")
s_Noyes<-read.csv(file = "data/Noyes.csv")
s_47th___South_Elevated<-read.csv(file = "data/47th-South_Elevated.csv")
s_Merchandise_Mart<-read.csv(file = "data/Merchandise_Mart.csv")
s_Midway_Airport<-read.csv(file = "data/Midway_Airport.csv")
s_43rd<-read.csv(file = "data/43rd.csv")
s_Western__Milwaukee<-read.csv(file = "data/Western__Milwaukee.csv")
s_Ashland___Lake<-read.csv(file = "data/Ashland-Lake.csv")
s_Belmont___OHare<-read.csv(file = "data/Belmont-O'Hare.csv")
s_Oak_Park___Lake<-read.csv(file = "data/Oak_Park-Lake.csv")
s_Conservatory<-read.csv(file = "data/Conservatory.csv")
s_Library<-read.csv(file = "data/Library.csv")
s_Loyola<-read.csv(file = "data/Loyola.csv")
s_Southport<-read.csv(file = "data/Southport.csv")
s_Montrose___OHare<-read.csv(file = "data/Montrose-O'Hare.csv")
s_Jarvis<-read.csv(file = "data/Jarvis.csv")
s_South_Boulevard<-read.csv(file = "data/South_Boulevard.csv")
s_Cicero___Forest_Park<-read.csv(file = "data/Cicero-Forest_Park.csv")
s_Medical_Center<-read.csv(file = "data/Medical_Center.csv")
s_Davis<-read.csv(file = "data/Davis.csv")
s_Clark__Division<-read.csv(file = "data/Clark__Division.csv")
s_Jackson__Dearborn<-read.csv(file = "data/Jackson__Dearborn.csv")
s_Washington__Wabash<-read.csv(file = "data/Washington__Wabash.csv")
s_Francisco<-read.csv(file = "data/Francisco.csv")
s_Central___Evanston<-read.csv(file = "data/Central-Evanston.csv")
s_Oakton___Skokie<-read.csv(file = "data/Oakton-Skokie.csv")
s_Austin___Lake<-read.csv(file = "data/Austin-Lake.csv")
s_Bryn_Mawr<-read.csv(file = "data/Bryn_Mawr.csv")
s_Kostner<-read.csv(file = "data/Kostner.csv")
s_Forest_Park<-read.csv(file = "data/Forest_Park.csv")
s_California___Lake<-read.csv(file = "data/California-Lake.csv")
s_Garfield___South_Elevated<-read.csv(file = "data/Garfield-South_Elevated.csv")
s_Rockwell<-read.csv(file = "data/Rockwell.csv")
s_Diversey<-read.csv(file = "data/Diversey.csv")
s_Argyle<-read.csv(file = "data/Argyle.csv")
s_LaSalle<-read.csv(file = "data/LaSalle.csv")
s_Monroe__Dearborn<-read.csv(file = "data/Monroe__Dearborn.csv")
s_Rosemont<-read.csv(file = "data/Rosemont.csv")
s_King_Drive<-read.csv(file = "data/King_Drive.csv")
s_Armitage<-read.csv(file = "data/Armitage.csv")
s_Thorndale<-read.csv(file = "data/Thorndale.csv")
s_Western___Brown<-read.csv(file = "data/Western-Brown.csv")
s_Skokie<-read.csv(file = "data/Skokie.csv")
s_Washington__State<-read.csv(file = "data/Washington__State.csv")
s_Homan<-read.csv(file = "data/Homan.csv")

s_Jefferson_Park$updated_date <- date((parse_date_time(s_Jefferson_Park$date,"mdy")))
s_Jefferson_Park$the_year <- year(s_Jefferson_Park$updated_date)
s_Jefferson_Park$the_month <- month(s_Jefferson_Park$updated_date,abbr = TRUE, label = TRUE)
s_Jefferson_Park$weekday <- wday(s_Jefferson_Park$updated_date, abbr = TRUE, label = TRUE)
s_Cermak___Chinatown$updated_date <- date((parse_date_time(s_Cermak___Chinatown$date,"mdy")))
s_Cermak___Chinatown$the_year <- year(s_Cermak___Chinatown$updated_date)
s_Cermak___Chinatown$the_month <- month(s_Cermak___Chinatown$updated_date,abbr = TRUE, label = TRUE)
s_Cermak___Chinatown$weekday <- wday(s_Cermak___Chinatown$updated_date, abbr = TRUE, label = TRUE)
s_Central___Lake$updated_date <- date((parse_date_time(s_Central___Lake$date,"mdy")))
s_Central___Lake$the_year <- year(s_Central___Lake$updated_date)
s_Central___Lake$the_month <- month(s_Central___Lake$updated_date,abbr = TRUE, label = TRUE)
s_Central___Lake$weekday <- wday(s_Central___Lake$updated_date, abbr = TRUE, label = TRUE)
s_Dempster___Skokie$updated_date <- date((parse_date_time(s_Dempster___Skokie$date,"mdy")))
s_Dempster___Skokie$the_year <- year(s_Dempster___Skokie$updated_date)
s_Dempster___Skokie$the_month <- month(s_Dempster___Skokie$updated_date,abbr = TRUE, label = TRUE)
s_Dempster___Skokie$weekday <- wday(s_Dempster___Skokie$updated_date, abbr = TRUE, label = TRUE)
s_Dempster$updated_date <- date((parse_date_time(s_Dempster$date,"mdy")))
s_Dempster$the_year <- year(s_Dempster$updated_date)
s_Dempster$the_month <- month(s_Dempster$updated_date,abbr = TRUE, label = TRUE)
s_Dempster$weekday <- wday(s_Dempster$updated_date, abbr = TRUE, label = TRUE)
s_Lake__State$updated_date <- date((parse_date_time(s_Lake__State$date,"mdy")))
s_Lake__State$the_year <- year(s_Lake__State$updated_date)
s_Lake__State$the_month <- month(s_Lake__State$updated_date,abbr = TRUE, label = TRUE)
s_Lake__State$weekday <- wday(s_Lake__State$updated_date, abbr = TRUE, label = TRUE)
s_Oak_Park___Forest_Park$updated_date <- date((parse_date_time(s_Oak_Park___Forest_Park$date,"mdy")))
s_Oak_Park___Forest_Park$the_year <- year(s_Oak_Park___Forest_Park$updated_date)
s_Oak_Park___Forest_Park$the_month <- month(s_Oak_Park___Forest_Park$updated_date,abbr = TRUE, label = TRUE)
s_Oak_Park___Forest_Park$weekday <- wday(s_Oak_Park___Forest_Park$updated_date, abbr = TRUE, label = TRUE)
s_Kedzie___Homan___Forest_Park$updated_date <- date((parse_date_time(s_Kedzie___Homan___Forest_Park$date,"mdy")))
s_Kedzie___Homan___Forest_Park$the_year <- year(s_Kedzie___Homan___Forest_Park$updated_date)
s_Kedzie___Homan___Forest_Park$the_month <- month(s_Kedzie___Homan___Forest_Park$updated_date,abbr = TRUE, label = TRUE)
s_Kedzie___Homan___Forest_Park$weekday <- wday(s_Kedzie___Homan___Forest_Park$updated_date, abbr = TRUE, label = TRUE)
s_35th__Archer$updated_date <- date((parse_date_time(s_35th__Archer$date,"mdy")))
s_35th__Archer$the_year <- year(s_35th__Archer$updated_date)
s_35th__Archer$the_month <- month(s_35th__Archer$updated_date,abbr = TRUE, label = TRUE)
s_35th__Archer$weekday <- wday(s_35th__Archer$updated_date, abbr = TRUE, label = TRUE)
s_Addison___North_Main$updated_date <- date((parse_date_time(s_Addison___North_Main$date,"mdy")))
s_Addison___North_Main$the_year <- year(s_Addison___North_Main$updated_date)
s_Addison___North_Main$the_month <- month(s_Addison___North_Main$updated_date,abbr = TRUE, label = TRUE)
s_Addison___North_Main$weekday <- wday(s_Addison___North_Main$updated_date, abbr = TRUE, label = TRUE)
s_Main$updated_date <- date((parse_date_time(s_Main$date,"mdy")))
s_Main$the_year <- year(s_Main$updated_date)
s_Main$the_month <- month(s_Main$updated_date,abbr = TRUE, label = TRUE)
s_Main$weekday <- wday(s_Main$updated_date, abbr = TRUE, label = TRUE)
s_Chicago__State$updated_date <- date((parse_date_time(s_Chicago__State$date,"mdy")))
s_Chicago__State$the_year <- year(s_Chicago__State$updated_date)
s_Chicago__State$the_month <- month(s_Chicago__State$updated_date,abbr = TRUE, label = TRUE)
s_Chicago__State$weekday <- wday(s_Chicago__State$updated_date, abbr = TRUE, label = TRUE)
s_Wellington$updated_date <- date((parse_date_time(s_Wellington$date,"mdy")))
s_Wellington$the_year <- year(s_Wellington$updated_date)
s_Wellington$the_month <- month(s_Wellington$updated_date,abbr = TRUE, label = TRUE)
s_Wellington$weekday <- wday(s_Wellington$updated_date, abbr = TRUE, label = TRUE)
s_Austin___Forest_Park$updated_date <- date((parse_date_time(s_Austin___Forest_Park$date,"mdy")))
s_Austin___Forest_Park$the_year <- year(s_Austin___Forest_Park$updated_date)
s_Austin___Forest_Park$the_month <- month(s_Austin___Forest_Park$updated_date,abbr = TRUE, label = TRUE)
s_Austin___Forest_Park$weekday <- wday(s_Austin___Forest_Park$updated_date, abbr = TRUE, label = TRUE)
s_Clinton___Lake$updated_date <- date((parse_date_time(s_Clinton___Lake$date,"mdy")))
s_Clinton___Lake$the_year <- year(s_Clinton___Lake$updated_date)
s_Clinton___Lake$the_month <- month(s_Clinton___Lake$updated_date,abbr = TRUE, label = TRUE)
s_Clinton___Lake$weekday <- wday(s_Clinton___Lake$updated_date, abbr = TRUE, label = TRUE)
s_East_63rd___Cottage_Grove$updated_date <- date((parse_date_time(s_East_63rd___Cottage_Grove$date,"mdy")))
s_East_63rd___Cottage_Grove$the_year <- year(s_East_63rd___Cottage_Grove$updated_date)
s_East_63rd___Cottage_Grove$the_month <- month(s_East_63rd___Cottage_Grove$updated_date,abbr = TRUE, label = TRUE)
s_East_63rd___Cottage_Grove$weekday <- wday(s_East_63rd___Cottage_Grove$updated_date, abbr = TRUE, label = TRUE)
s_Grand__State$updated_date <- date((parse_date_time(s_Grand__State$date,"mdy")))
s_Grand__State$the_year <- year(s_Grand__State$updated_date)
s_Grand__State$the_month <- month(s_Grand__State$updated_date,abbr = TRUE, label = TRUE)
s_Grand__State$weekday <- wday(s_Grand__State$updated_date, abbr = TRUE, label = TRUE)
s_Wilson$updated_date <- date((parse_date_time(s_Wilson$date,"mdy")))
s_Wilson$the_year <- year(s_Wilson$updated_date)
s_Wilson$the_month <- month(s_Wilson$updated_date,abbr = TRUE, label = TRUE)
s_Wilson$weekday <- wday(s_Wilson$updated_date, abbr = TRUE, label = TRUE)
s_Cicero___Cermak$updated_date <- date((parse_date_time(s_Cicero___Cermak$date,"mdy")))
s_Cicero___Cermak$the_year <- year(s_Cicero___Cermak$updated_date)
s_Cicero___Cermak$the_month <- month(s_Cicero___Cermak$updated_date,abbr = TRUE, label = TRUE)
s_Cicero___Cermak$weekday <- wday(s_Cicero___Cermak$updated_date, abbr = TRUE, label = TRUE)
s_State__Lake$updated_date <- date((parse_date_time(s_State__Lake$date,"mdy")))
s_State__Lake$the_year <- year(s_State__Lake$updated_date)
s_State__Lake$the_month <- month(s_State__Lake$updated_date,abbr = TRUE, label = TRUE)
s_State__Lake$weekday <- wday(s_State__Lake$updated_date, abbr = TRUE, label = TRUE)
s_51st$updated_date <- date((parse_date_time(s_51st$date,"mdy")))
s_51st$the_year <- year(s_51st$updated_date)
s_51st$the_month <- month(s_51st$updated_date,abbr = TRUE, label = TRUE)
s_51st$weekday <- wday(s_51st$updated_date, abbr = TRUE, label = TRUE)
s_95th__Dan_Ryan$updated_date <- date((parse_date_time(s_95th__Dan_Ryan$date,"mdy")))
s_95th__Dan_Ryan$the_year <- year(s_95th__Dan_Ryan$updated_date)
s_95th__Dan_Ryan$the_month <- month(s_95th__Dan_Ryan$updated_date,abbr = TRUE, label = TRUE)
s_95th__Dan_Ryan$weekday <- wday(s_95th__Dan_Ryan$updated_date, abbr = TRUE, label = TRUE)
s_Jackson__State$updated_date <- date((parse_date_time(s_Jackson__State$date,"mdy")))
s_Jackson__State$the_year <- year(s_Jackson__State$updated_date)
s_Jackson__State$the_month <- month(s_Jackson__State$updated_date,abbr = TRUE, label = TRUE)
s_Jackson__State$weekday <- wday(s_Jackson__State$updated_date, abbr = TRUE, label = TRUE)
s_Randolph__Wabash$updated_date <- date((parse_date_time(s_Randolph__Wabash$date,"mdy")))
s_Randolph__Wabash$the_year <- year(s_Randolph__Wabash$updated_date)
s_Randolph__Wabash$the_month <- month(s_Randolph__Wabash$updated_date,abbr = TRUE, label = TRUE)
s_Randolph__Wabash$weekday <- wday(s_Randolph__Wabash$updated_date, abbr = TRUE, label = TRUE)
s_Logan_Square$updated_date <- date((parse_date_time(s_Logan_Square$date,"mdy")))
s_Logan_Square$the_year <- year(s_Logan_Square$updated_date)
s_Logan_Square$the_month <- month(s_Logan_Square$updated_date,abbr = TRUE, label = TRUE)
s_Logan_Square$weekday <- wday(s_Logan_Square$updated_date, abbr = TRUE, label = TRUE)
s_Morse$updated_date <- date((parse_date_time(s_Morse$date,"mdy")))
s_Morse$the_year <- year(s_Morse$updated_date)
s_Morse$the_month <- month(s_Morse$updated_date,abbr = TRUE, label = TRUE)
s_Morse$weekday <- wday(s_Morse$updated_date, abbr = TRUE, label = TRUE)
s_Grand__Milwaukee$updated_date <- date((parse_date_time(s_Grand__Milwaukee$date,"mdy")))
s_Grand__Milwaukee$the_year <- year(s_Grand__Milwaukee$updated_date)
s_Grand__Milwaukee$the_month <- month(s_Grand__Milwaukee$updated_date,abbr = TRUE, label = TRUE)
s_Grand__Milwaukee$weekday <- wday(s_Grand__Milwaukee$updated_date, abbr = TRUE, label = TRUE)
s_69th$updated_date <- date((parse_date_time(s_69th$date,"mdy")))
s_69th$the_year <- year(s_69th$updated_date)
s_69th$the_month <- month(s_69th$updated_date,abbr = TRUE, label = TRUE)
s_69th$weekday <- wday(s_69th$updated_date, abbr = TRUE, label = TRUE)
s_Paulina$updated_date <- date((parse_date_time(s_Paulina$date,"mdy")))
s_Paulina$the_year <- year(s_Paulina$updated_date)
s_Paulina$the_month <- month(s_Paulina$updated_date,abbr = TRUE, label = TRUE)
s_Paulina$weekday <- wday(s_Paulina$updated_date, abbr = TRUE, label = TRUE)
s_Damen___Brown$updated_date <- date((parse_date_time(s_Damen___Brown$date,"mdy")))
s_Damen___Brown$the_year <- year(s_Damen___Brown$updated_date)
s_Damen___Brown$the_month <- month(s_Damen___Brown$updated_date,abbr = TRUE, label = TRUE)
s_Damen___Brown$weekday <- wday(s_Damen___Brown$updated_date, abbr = TRUE, label = TRUE)
s_Washington__Dearborn$updated_date <- date((parse_date_time(s_Washington__Dearborn$date,"mdy")))
s_Washington__Dearborn$the_year <- year(s_Washington__Dearborn$updated_date)
s_Washington__Dearborn$the_month <- month(s_Washington__Dearborn$updated_date,abbr = TRUE, label = TRUE)
s_Washington__Dearborn$weekday <- wday(s_Washington__Dearborn$updated_date, abbr = TRUE, label = TRUE)
s_Kimball$updated_date <- date((parse_date_time(s_Kimball$date,"mdy")))
s_Kimball$the_year <- year(s_Kimball$updated_date)
s_Kimball$the_month <- month(s_Kimball$updated_date,abbr = TRUE, label = TRUE)
s_Kimball$weekday <- wday(s_Kimball$updated_date, abbr = TRUE, label = TRUE)
s_Clark__Lake$updated_date <- date((parse_date_time(s_Clark__Lake$date,"mdy")))
s_Clark__Lake$the_year <- year(s_Clark__Lake$updated_date)
s_Clark__Lake$the_month <- month(s_Clark__Lake$updated_date,abbr = TRUE, label = TRUE)
s_Clark__Lake$weekday <- wday(s_Clark__Lake$updated_date, abbr = TRUE, label = TRUE)
s_Lawrence$updated_date <- date((parse_date_time(s_Lawrence$date,"mdy")))
s_Lawrence$the_year <- year(s_Lawrence$updated_date)
s_Lawrence$the_month <- month(s_Lawrence$updated_date,abbr = TRUE, label = TRUE)
s_Lawrence$weekday <- wday(s_Lawrence$updated_date, abbr = TRUE, label = TRUE)
s_Polk$updated_date <- date((parse_date_time(s_Polk$date,"mdy")))
s_Polk$the_year <- year(s_Polk$updated_date)
s_Polk$the_month <- month(s_Polk$updated_date,abbr = TRUE, label = TRUE)
s_Polk$weekday <- wday(s_Polk$updated_date, abbr = TRUE, label = TRUE)
s_47th___Dan_Ryan$updated_date <- date((parse_date_time(s_47th___Dan_Ryan$date,"mdy")))
s_47th___Dan_Ryan$the_year <- year(s_47th___Dan_Ryan$updated_date)
s_47th___Dan_Ryan$the_month <- month(s_47th___Dan_Ryan$updated_date,abbr = TRUE, label = TRUE)
s_47th___Dan_Ryan$weekday <- wday(s_47th___Dan_Ryan$updated_date, abbr = TRUE, label = TRUE)
s_Sedgwick$updated_date <- date((parse_date_time(s_Sedgwick$date,"mdy")))
s_Sedgwick$the_year <- year(s_Sedgwick$updated_date)
s_Sedgwick$the_month <- month(s_Sedgwick$updated_date,abbr = TRUE, label = TRUE)
s_Sedgwick$weekday <- wday(s_Sedgwick$updated_date, abbr = TRUE, label = TRUE)
s_54th__Cermak$updated_date <- date((parse_date_time(s_54th__Cermak$date,"mdy")))
s_54th__Cermak$the_year <- year(s_54th__Cermak$updated_date)
s_54th__Cermak$the_month <- month(s_54th__Cermak$updated_date,abbr = TRUE, label = TRUE)
s_54th__Cermak$weekday <- wday(s_54th__Cermak$updated_date, abbr = TRUE, label = TRUE)
s_Ashland__63rd$updated_date <- date((parse_date_time(s_Ashland__63rd$date,"mdy")))
s_Ashland__63rd$the_year <- year(s_Ashland__63rd$updated_date)
s_Ashland__63rd$the_month <- month(s_Ashland__63rd$updated_date,abbr = TRUE, label = TRUE)
s_Ashland__63rd$weekday <- wday(s_Ashland__63rd$updated_date, abbr = TRUE, label = TRUE)
s_Morgan___Lake$updated_date <- date((parse_date_time(s_Morgan___Lake$date,"mdy")))
s_Morgan___Lake$the_year <- year(s_Morgan___Lake$updated_date)
s_Morgan___Lake$the_month <- month(s_Morgan___Lake$updated_date,abbr = TRUE, label = TRUE)
s_Morgan___Lake$weekday <- wday(s_Morgan___Lake$updated_date, abbr = TRUE, label = TRUE)
s_Harrison$updated_date <- date((parse_date_time(s_Harrison$date,"mdy")))
s_Harrison$the_year <- year(s_Harrison$updated_date)
s_Harrison$the_month <- month(s_Harrison$updated_date,abbr = TRUE, label = TRUE)
s_Harrison$weekday <- wday(s_Harrison$updated_date, abbr = TRUE, label = TRUE)
s_Sheridan$updated_date <- date((parse_date_time(s_Sheridan$date,"mdy")))
s_Sheridan$the_year <- year(s_Sheridan$updated_date)
s_Sheridan$the_month <- month(s_Sheridan$updated_date,abbr = TRUE, label = TRUE)
s_Sheridan$weekday <- wday(s_Sheridan$updated_date, abbr = TRUE, label = TRUE)
s_Racine$updated_date <- date((parse_date_time(s_Racine$date,"mdy")))
s_Racine$the_year <- year(s_Racine$updated_date)
s_Racine$the_month <- month(s_Racine$updated_date,abbr = TRUE, label = TRUE)
s_Racine$weekday <- wday(s_Racine$updated_date, abbr = TRUE, label = TRUE)
s_Washington__Wells$updated_date <- date((parse_date_time(s_Washington__Wells$date,"mdy")))
s_Washington__Wells$the_year <- year(s_Washington__Wells$updated_date)
s_Washington__Wells$the_month <- month(s_Washington__Wells$updated_date,abbr = TRUE, label = TRUE)
s_Washington__Wells$weekday <- wday(s_Washington__Wells$updated_date, abbr = TRUE, label = TRUE)
s_Quincy__Wells$updated_date <- date((parse_date_time(s_Quincy__Wells$date,"mdy")))
s_Quincy__Wells$the_year <- year(s_Quincy__Wells$updated_date)
s_Quincy__Wells$the_month <- month(s_Quincy__Wells$updated_date,abbr = TRUE, label = TRUE)
s_Quincy__Wells$weekday <- wday(s_Quincy__Wells$updated_date, abbr = TRUE, label = TRUE)
s_Foster$updated_date <- date((parse_date_time(s_Foster$date,"mdy")))
s_Foster$the_year <- year(s_Foster$updated_date)
s_Foster$the_month <- month(s_Foster$updated_date,abbr = TRUE, label = TRUE)
s_Foster$weekday <- wday(s_Foster$updated_date, abbr = TRUE, label = TRUE)
s_California__Milwaukee$updated_date <- date((parse_date_time(s_California__Milwaukee$date,"mdy")))
s_California__Milwaukee$the_year <- year(s_California__Milwaukee$updated_date)
s_California__Milwaukee$the_month <- month(s_California__Milwaukee$updated_date,abbr = TRUE, label = TRUE)
s_California__Milwaukee$weekday <- wday(s_California__Milwaukee$updated_date, abbr = TRUE, label = TRUE)
s_Cermak___McCormick_Place$updated_date <- date((parse_date_time(s_Cermak___McCormick_Place$date,"mdy")))
s_Cermak___McCormick_Place$the_year <- year(s_Cermak___McCormick_Place$updated_date)
s_Cermak___McCormick_Place$the_month <- month(s_Cermak___McCormick_Place$updated_date,abbr = TRUE, label = TRUE)
s_Cermak___McCormick_Place$weekday <- wday(s_Cermak___McCormick_Place$updated_date, abbr = TRUE, label = TRUE)
s_Sox___35th___Dan_Ryan$updated_date <- date((parse_date_time(s_Sox___35th___Dan_Ryan$date,"mdy")))
s_Sox___35th___Dan_Ryan$the_year <- year(s_Sox___35th___Dan_Ryan$updated_date)
s_Sox___35th___Dan_Ryan$the_month <- month(s_Sox___35th___Dan_Ryan$updated_date,abbr = TRUE, label = TRUE)
s_Sox___35th___Dan_Ryan$weekday <- wday(s_Sox___35th___Dan_Ryan$updated_date, abbr = TRUE, label = TRUE)
s_Chicago__Milwaukee$updated_date <- date((parse_date_time(s_Chicago__Milwaukee$date,"mdy")))
s_Chicago__Milwaukee$the_year <- year(s_Chicago__Milwaukee$updated_date)
s_Chicago__Milwaukee$the_month <- month(s_Chicago__Milwaukee$updated_date,abbr = TRUE, label = TRUE)
s_Chicago__Milwaukee$weekday <- wday(s_Chicago__Milwaukee$updated_date, abbr = TRUE, label = TRUE)
s_OHare_Airport$updated_date <- date((parse_date_time(s_OHare_Airport$date,"mdy")))
s_OHare_Airport$the_year <- year(s_OHare_Airport$updated_date)
s_OHare_Airport$the_month <- month(s_OHare_Airport$updated_date,abbr = TRUE, label = TRUE)
s_OHare_Airport$weekday <- wday(s_OHare_Airport$updated_date, abbr = TRUE, label = TRUE)
s_Kedzie___Lake$updated_date <- date((parse_date_time(s_Kedzie___Lake$date,"mdy")))
s_Kedzie___Lake$the_year <- year(s_Kedzie___Lake$updated_date)
s_Kedzie___Lake$the_month <- month(s_Kedzie___Lake$updated_date,abbr = TRUE, label = TRUE)
s_Kedzie___Lake$weekday <- wday(s_Kedzie___Lake$updated_date, abbr = TRUE, label = TRUE)
s_Fullerton$updated_date <- date((parse_date_time(s_Fullerton$date,"mdy")))
s_Fullerton$the_year <- year(s_Fullerton$updated_date)
s_Fullerton$the_month <- month(s_Fullerton$updated_date,abbr = TRUE, label = TRUE)
s_Fullerton$weekday <- wday(s_Fullerton$updated_date, abbr = TRUE, label = TRUE)
s_Irving_Park___Brown$updated_date <- date((parse_date_time(s_Irving_Park___Brown$date,"mdy")))
s_Irving_Park___Brown$the_year <- year(s_Irving_Park___Brown$updated_date)
s_Irving_Park___Brown$the_month <- month(s_Irving_Park___Brown$updated_date,abbr = TRUE, label = TRUE)
s_Irving_Park___Brown$weekday <- wday(s_Irving_Park___Brown$updated_date, abbr = TRUE, label = TRUE)
s_LaSalle__Van_Buren$updated_date <- date((parse_date_time(s_LaSalle__Van_Buren$date,"mdy")))
s_LaSalle__Van_Buren$the_year <- year(s_LaSalle__Van_Buren$updated_date)
s_LaSalle__Van_Buren$the_month <- month(s_LaSalle__Van_Buren$updated_date,abbr = TRUE, label = TRUE)
s_LaSalle__Van_Buren$weekday <- wday(s_LaSalle__Van_Buren$updated_date, abbr = TRUE, label = TRUE)
s_Belmont___North_Main$updated_date <- date((parse_date_time(s_Belmont___North_Main$date,"mdy")))
s_Belmont___North_Main$the_year <- year(s_Belmont___North_Main$updated_date)
s_Belmont___North_Main$the_month <- month(s_Belmont___North_Main$updated_date,abbr = TRUE, label = TRUE)
s_Belmont___North_Main$weekday <- wday(s_Belmont___North_Main$updated_date, abbr = TRUE, label = TRUE)
s_79th$updated_date <- date((parse_date_time(s_79th$date,"mdy")))
s_79th$the_year <- year(s_79th$updated_date)
s_79th$the_month <- month(s_79th$updated_date,abbr = TRUE, label = TRUE)
s_79th$weekday <- wday(s_79th$updated_date, abbr = TRUE, label = TRUE)
s_Adams__Wabash$updated_date <- date((parse_date_time(s_Adams__Wabash$date,"mdy")))
s_Adams__Wabash$the_year <- year(s_Adams__Wabash$updated_date)
s_Adams__Wabash$the_month <- month(s_Adams__Wabash$updated_date,abbr = TRUE, label = TRUE)
s_Adams__Wabash$weekday <- wday(s_Adams__Wabash$updated_date, abbr = TRUE, label = TRUE)
s_Western___Orange$updated_date <- date((parse_date_time(s_Western___Orange$date,"mdy")))
s_Western___Orange$the_year <- year(s_Western___Orange$updated_date)
s_Western___Orange$the_month <- month(s_Western___Orange$updated_date,abbr = TRUE, label = TRUE)
s_Western___Orange$weekday <- wday(s_Western___Orange$updated_date, abbr = TRUE, label = TRUE)
s_Clinton___Forest_Park$updated_date <- date((parse_date_time(s_Clinton___Forest_Park$date,"mdy")))
s_Clinton___Forest_Park$the_year <- year(s_Clinton___Forest_Park$updated_date)
s_Clinton___Forest_Park$the_month <- month(s_Clinton___Forest_Park$updated_date,abbr = TRUE, label = TRUE)
s_Clinton___Forest_Park$weekday <- wday(s_Clinton___Forest_Park$updated_date, abbr = TRUE, label = TRUE)
s_UIC___Halsted$updated_date <- date((parse_date_time(s_UIC___Halsted$date,"mdy")))
s_UIC___Halsted$the_year <- year(s_UIC___Halsted$updated_date)
s_UIC___Halsted$the_month <- month(s_UIC___Halsted$updated_date,abbr = TRUE, label = TRUE)
s_UIC___Halsted$weekday <- wday(s_UIC___Halsted$updated_date, abbr = TRUE, label = TRUE)
s_35___Bronzeville___IIT$updated_date <- date((parse_date_time(s_35___Bronzeville___IIT$date,"mdy")))
s_35___Bronzeville___IIT$the_year <- year(s_35___Bronzeville___IIT$updated_date)
s_35___Bronzeville___IIT$the_month <- month(s_35___Bronzeville___IIT$updated_date,abbr = TRUE, label = TRUE)
s_35___Bronzeville___IIT$weekday <- wday(s_35___Bronzeville___IIT$updated_date, abbr = TRUE, label = TRUE)
s_87th$updated_date <- date((parse_date_time(s_87th$date,"mdy")))
s_87th$the_year <- year(s_87th$updated_date)
s_87th$the_month <- month(s_87th$updated_date,abbr = TRUE, label = TRUE)
s_87th$weekday <- wday(s_87th$updated_date, abbr = TRUE, label = TRUE)
s_18th$updated_date <- date((parse_date_time(s_18th$date,"mdy")))
s_18th$the_year <- year(s_18th$updated_date)
s_18th$the_month <- month(s_18th$updated_date,abbr = TRUE, label = TRUE)
s_18th$weekday <- wday(s_18th$updated_date, abbr = TRUE, label = TRUE)
s_Indiana$updated_date <- date((parse_date_time(s_Indiana$date,"mdy")))
s_Indiana$the_year <- year(s_Indiana$updated_date)
s_Indiana$the_month <- month(s_Indiana$updated_date,abbr = TRUE, label = TRUE)
s_Indiana$weekday <- wday(s_Indiana$updated_date, abbr = TRUE, label = TRUE)
s_Monroe__State$updated_date <- date((parse_date_time(s_Monroe__State$date,"mdy")))
s_Monroe__State$the_year <- year(s_Monroe__State$updated_date)
s_Monroe__State$the_month <- month(s_Monroe__State$updated_date,abbr = TRUE, label = TRUE)
s_Monroe__State$weekday <- wday(s_Monroe__State$updated_date, abbr = TRUE, label = TRUE)
s_Irving_Park___OHare$updated_date <- date((parse_date_time(s_Irving_Park___OHare$date,"mdy")))
s_Irving_Park___OHare$the_year <- year(s_Irving_Park___OHare$updated_date)
s_Irving_Park___OHare$the_month <- month(s_Irving_Park___OHare$updated_date,abbr = TRUE, label = TRUE)
s_Irving_Park___OHare$weekday <- wday(s_Irving_Park___OHare$updated_date, abbr = TRUE, label = TRUE)
s_Cumberland$updated_date <- date((parse_date_time(s_Cumberland$date,"mdy")))
s_Cumberland$the_year <- year(s_Cumberland$updated_date)
s_Cumberland$the_month <- month(s_Cumberland$updated_date,abbr = TRUE, label = TRUE)
s_Cumberland$weekday <- wday(s_Cumberland$updated_date, abbr = TRUE, label = TRUE)
s_Roosevelt$updated_date <- date((parse_date_time(s_Roosevelt$date,"mdy")))
s_Roosevelt$the_year <- year(s_Roosevelt$updated_date)
s_Roosevelt$the_month <- month(s_Roosevelt$updated_date,abbr = TRUE, label = TRUE)
s_Roosevelt$weekday <- wday(s_Roosevelt$updated_date, abbr = TRUE, label = TRUE)
s_Damen__Milwaukee$updated_date <- date((parse_date_time(s_Damen__Milwaukee$date,"mdy")))
s_Damen__Milwaukee$the_year <- year(s_Damen__Milwaukee$updated_date)
s_Damen__Milwaukee$the_month <- month(s_Damen__Milwaukee$updated_date,abbr = TRUE, label = TRUE)
s_Damen__Milwaukee$weekday <- wday(s_Damen__Milwaukee$updated_date, abbr = TRUE, label = TRUE)
s_Kedzie___Midway$updated_date <- date((parse_date_time(s_Kedzie___Midway$date,"mdy")))
s_Kedzie___Midway$the_year <- year(s_Kedzie___Midway$updated_date)
s_Kedzie___Midway$the_month <- month(s_Kedzie___Midway$updated_date,abbr = TRUE, label = TRUE)
s_Kedzie___Midway$weekday <- wday(s_Kedzie___Midway$updated_date, abbr = TRUE, label = TRUE)
s_63rd___Dan_Ryan$updated_date <- date((parse_date_time(s_63rd___Dan_Ryan$date,"mdy")))
s_63rd___Dan_Ryan$the_year <- year(s_63rd___Dan_Ryan$updated_date)
s_63rd___Dan_Ryan$the_month <- month(s_63rd___Dan_Ryan$updated_date,abbr = TRUE, label = TRUE)
s_63rd___Dan_Ryan$weekday <- wday(s_63rd___Dan_Ryan$updated_date, abbr = TRUE, label = TRUE)
s_Kedzie___Cermak$updated_date <- date((parse_date_time(s_Kedzie___Cermak$date,"mdy")))
s_Kedzie___Cermak$the_year <- year(s_Kedzie___Cermak$updated_date)
s_Kedzie___Cermak$the_month <- month(s_Kedzie___Cermak$updated_date,abbr = TRUE, label = TRUE)
s_Kedzie___Cermak$weekday <- wday(s_Kedzie___Cermak$updated_date, abbr = TRUE, label = TRUE)
s_Addison___Brown$updated_date <- date((parse_date_time(s_Addison___Brown$date,"mdy")))
s_Addison___Brown$the_year <- year(s_Addison___Brown$updated_date)
s_Addison___Brown$the_month <- month(s_Addison___Brown$updated_date,abbr = TRUE, label = TRUE)
s_Addison___Brown$weekday <- wday(s_Addison___Brown$updated_date, abbr = TRUE, label = TRUE)
s_Division__Milwaukee$updated_date <- date((parse_date_time(s_Division__Milwaukee$date,"mdy")))
s_Division__Milwaukee$the_year <- year(s_Division__Milwaukee$updated_date)
s_Division__Milwaukee$the_month <- month(s_Division__Milwaukee$updated_date,abbr = TRUE, label = TRUE)
s_Division__Milwaukee$weekday <- wday(s_Division__Milwaukee$updated_date, abbr = TRUE, label = TRUE)
s_Damen___Cermak$updated_date <- date((parse_date_time(s_Damen___Cermak$date,"mdy")))
s_Damen___Cermak$the_year <- year(s_Damen___Cermak$updated_date)
s_Damen___Cermak$the_month <- month(s_Damen___Cermak$updated_date,abbr = TRUE, label = TRUE)
s_Damen___Cermak$weekday <- wday(s_Damen___Cermak$updated_date, abbr = TRUE, label = TRUE)
s_Cicero___Lake$updated_date <- date((parse_date_time(s_Cicero___Lake$date,"mdy")))
s_Cicero___Lake$the_year <- year(s_Cicero___Lake$updated_date)
s_Cicero___Lake$the_month <- month(s_Cicero___Lake$updated_date,abbr = TRUE, label = TRUE)
s_Cicero___Lake$weekday <- wday(s_Cicero___Lake$updated_date, abbr = TRUE, label = TRUE)
s_Madison__Wabash$updated_date <- date((parse_date_time(s_Madison__Wabash$date,"mdy")))
s_Madison__Wabash$the_year <- year(s_Madison__Wabash$updated_date)
s_Madison__Wabash$the_month <- month(s_Madison__Wabash$updated_date,abbr = TRUE, label = TRUE)
s_Madison__Wabash$weekday <- wday(s_Madison__Wabash$updated_date, abbr = TRUE, label = TRUE)
s_Harlem___Lake$updated_date <- date((parse_date_time(s_Harlem___Lake$date,"mdy")))
s_Harlem___Lake$the_year <- year(s_Harlem___Lake$updated_date)
s_Harlem___Lake$the_month <- month(s_Harlem___Lake$updated_date,abbr = TRUE, label = TRUE)
s_Harlem___Lake$weekday <- wday(s_Harlem___Lake$updated_date, abbr = TRUE, label = TRUE)
s_Pulaski___Cermak$updated_date <- date((parse_date_time(s_Pulaski___Cermak$date,"mdy")))
s_Pulaski___Cermak$the_year <- year(s_Pulaski___Cermak$updated_date)
s_Pulaski___Cermak$the_month <- month(s_Pulaski___Cermak$updated_date,abbr = TRUE, label = TRUE)
s_Pulaski___Cermak$weekday <- wday(s_Pulaski___Cermak$updated_date, abbr = TRUE, label = TRUE)
s_Kedzie___Brown$updated_date <- date((parse_date_time(s_Kedzie___Brown$date,"mdy")))
s_Kedzie___Brown$the_year <- year(s_Kedzie___Brown$updated_date)
s_Kedzie___Brown$the_month <- month(s_Kedzie___Brown$updated_date,abbr = TRUE, label = TRUE)
s_Kedzie___Brown$weekday <- wday(s_Kedzie___Brown$updated_date, abbr = TRUE, label = TRUE)
s_Central_Park$updated_date <- date((parse_date_time(s_Central_Park$date,"mdy")))
s_Central_Park$the_year <- year(s_Central_Park$updated_date)
s_Central_Park$the_month <- month(s_Central_Park$updated_date,abbr = TRUE, label = TRUE)
s_Central_Park$weekday <- wday(s_Central_Park$updated_date, abbr = TRUE, label = TRUE)
s_Harlem___OHare$updated_date <- date((parse_date_time(s_Harlem___OHare$date,"mdy")))
s_Harlem___OHare$the_year <- year(s_Harlem___OHare$updated_date)
s_Harlem___OHare$the_month <- month(s_Harlem___OHare$updated_date,abbr = TRUE, label = TRUE)
s_Harlem___OHare$weekday <- wday(s_Harlem___OHare$updated_date, abbr = TRUE, label = TRUE)
s_Chicago__Franklin$updated_date <- date((parse_date_time(s_Chicago__Franklin$date,"mdy")))
s_Chicago__Franklin$the_year <- year(s_Chicago__Franklin$updated_date)
s_Chicago__Franklin$the_month <- month(s_Chicago__Franklin$updated_date,abbr = TRUE, label = TRUE)
s_Chicago__Franklin$weekday <- wday(s_Chicago__Franklin$updated_date, abbr = TRUE, label = TRUE)
s_North__Clybourn$updated_date <- date((parse_date_time(s_North__Clybourn$date,"mdy")))
s_North__Clybourn$the_year <- year(s_North__Clybourn$updated_date)
s_North__Clybourn$the_month <- month(s_North__Clybourn$updated_date,abbr = TRUE, label = TRUE)
s_North__Clybourn$weekday <- wday(s_North__Clybourn$updated_date, abbr = TRUE, label = TRUE)
s_Berwyn$updated_date <- date((parse_date_time(s_Berwyn$date,"mdy")))
s_Berwyn$the_year <- year(s_Berwyn$updated_date)
s_Berwyn$the_month <- month(s_Berwyn$updated_date,abbr = TRUE, label = TRUE)
s_Berwyn$weekday <- wday(s_Berwyn$updated_date, abbr = TRUE, label = TRUE)
s_Laramie$updated_date <- date((parse_date_time(s_Laramie$date,"mdy")))
s_Laramie$the_year <- year(s_Laramie$updated_date)
s_Laramie$the_month <- month(s_Laramie$updated_date,abbr = TRUE, label = TRUE)
s_Laramie$weekday <- wday(s_Laramie$updated_date, abbr = TRUE, label = TRUE)
s_Howard$updated_date <- date((parse_date_time(s_Howard$date,"mdy")))
s_Howard$the_year <- year(s_Howard$updated_date)
s_Howard$the_month <- month(s_Howard$updated_date,abbr = TRUE, label = TRUE)
s_Howard$weekday <- wday(s_Howard$updated_date, abbr = TRUE, label = TRUE)
s_Granville$updated_date <- date((parse_date_time(s_Granville$date,"mdy")))
s_Granville$the_year <- year(s_Granville$updated_date)
s_Granville$the_month <- month(s_Granville$updated_date,abbr = TRUE, label = TRUE)
s_Granville$weekday <- wday(s_Granville$updated_date, abbr = TRUE, label = TRUE)
s_Western___Forest_Park$updated_date <- date((parse_date_time(s_Western___Forest_Park$date,"mdy")))
s_Western___Forest_Park$the_year <- year(s_Western___Forest_Park$updated_date)
s_Western___Forest_Park$the_month <- month(s_Western___Forest_Park$updated_date,abbr = TRUE, label = TRUE)
s_Western___Forest_Park$weekday <- wday(s_Western___Forest_Park$updated_date, abbr = TRUE, label = TRUE)
s_California___Cermak$updated_date <- date((parse_date_time(s_California___Cermak$date,"mdy")))
s_California___Cermak$the_year <- year(s_California___Cermak$updated_date)
s_California___Cermak$the_month <- month(s_California___Cermak$updated_date,abbr = TRUE, label = TRUE)
s_California___Cermak$weekday <- wday(s_California___Cermak$updated_date, abbr = TRUE, label = TRUE)
s_Ridgeland$updated_date <- date((parse_date_time(s_Ridgeland$date,"mdy")))
s_Ridgeland$the_year <- year(s_Ridgeland$updated_date)
s_Ridgeland$the_month <- month(s_Ridgeland$updated_date,abbr = TRUE, label = TRUE)
s_Ridgeland$weekday <- wday(s_Ridgeland$updated_date, abbr = TRUE, label = TRUE)
s_Western___Cermak$updated_date <- date((parse_date_time(s_Western___Cermak$date,"mdy")))
s_Western___Cermak$the_year <- year(s_Western___Cermak$updated_date)
s_Western___Cermak$the_month <- month(s_Western___Cermak$updated_date,abbr = TRUE, label = TRUE)
s_Western___Cermak$weekday <- wday(s_Western___Cermak$updated_date, abbr = TRUE, label = TRUE)
s_Halsted__63rd$updated_date <- date((parse_date_time(s_Halsted__63rd$date,"mdy")))
s_Halsted__63rd$the_year <- year(s_Halsted__63rd$updated_date)
s_Halsted__63rd$the_month <- month(s_Halsted__63rd$updated_date,abbr = TRUE, label = TRUE)
s_Halsted__63rd$weekday <- wday(s_Halsted__63rd$updated_date, abbr = TRUE, label = TRUE)
s_Pulaski___Forest_Park$updated_date <- date((parse_date_time(s_Pulaski___Forest_Park$date,"mdy")))
s_Pulaski___Forest_Park$the_year <- year(s_Pulaski___Forest_Park$updated_date)
s_Pulaski___Forest_Park$the_month <- month(s_Pulaski___Forest_Park$updated_date,abbr = TRUE, label = TRUE)
s_Pulaski___Forest_Park$weekday <- wday(s_Pulaski___Forest_Park$updated_date, abbr = TRUE, label = TRUE)
s_Montrose___Brown$updated_date <- date((parse_date_time(s_Montrose___Brown$date,"mdy")))
s_Montrose___Brown$the_year <- year(s_Montrose___Brown$updated_date)
s_Montrose___Brown$the_month <- month(s_Montrose___Brown$updated_date,abbr = TRUE, label = TRUE)
s_Montrose___Brown$weekday <- wday(s_Montrose___Brown$updated_date, abbr = TRUE, label = TRUE)
s_Linden$updated_date <- date((parse_date_time(s_Linden$date,"mdy")))
s_Linden$the_year <- year(s_Linden$updated_date)
s_Linden$the_month <- month(s_Linden$updated_date,abbr = TRUE, label = TRUE)
s_Linden$weekday <- wday(s_Linden$updated_date, abbr = TRUE, label = TRUE)
s_Pulaski___Lake$updated_date <- date((parse_date_time(s_Pulaski___Lake$date,"mdy")))
s_Pulaski___Lake$the_year <- year(s_Pulaski___Lake$updated_date)
s_Pulaski___Lake$the_month <- month(s_Pulaski___Lake$updated_date,abbr = TRUE, label = TRUE)
s_Pulaski___Lake$weekday <- wday(s_Pulaski___Lake$updated_date, abbr = TRUE, label = TRUE)
s_Harlem___Forest_Park$updated_date <- date((parse_date_time(s_Harlem___Forest_Park$date,"mdy")))
s_Harlem___Forest_Park$the_year <- year(s_Harlem___Forest_Park$updated_date)
s_Harlem___Forest_Park$the_month <- month(s_Harlem___Forest_Park$updated_date,abbr = TRUE, label = TRUE)
s_Harlem___Forest_Park$weekday <- wday(s_Harlem___Forest_Park$updated_date, abbr = TRUE, label = TRUE)
s_Ashland___Orange$updated_date <- date((parse_date_time(s_Ashland___Orange$date,"mdy")))
s_Ashland___Orange$the_year <- year(s_Ashland___Orange$updated_date)
s_Ashland___Orange$the_month <- month(s_Ashland___Orange$updated_date,abbr = TRUE, label = TRUE)
s_Ashland___Orange$weekday <- wday(s_Ashland___Orange$updated_date, abbr = TRUE, label = TRUE)
s_Garfield___Dan_Ryan$updated_date <- date((parse_date_time(s_Garfield___Dan_Ryan$date,"mdy")))
s_Garfield___Dan_Ryan$the_year <- year(s_Garfield___Dan_Ryan$updated_date)
s_Garfield___Dan_Ryan$the_month <- month(s_Garfield___Dan_Ryan$updated_date,abbr = TRUE, label = TRUE)
s_Garfield___Dan_Ryan$weekday <- wday(s_Garfield___Dan_Ryan$updated_date, abbr = TRUE, label = TRUE)
s_Halsted___Orange$updated_date <- date((parse_date_time(s_Halsted___Orange$date,"mdy")))
s_Halsted___Orange$the_year <- year(s_Halsted___Orange$updated_date)
s_Halsted___Orange$the_month <- month(s_Halsted___Orange$updated_date,abbr = TRUE, label = TRUE)
s_Halsted___Orange$weekday <- wday(s_Halsted___Orange$updated_date, abbr = TRUE, label = TRUE)
s_Addison___OHare$updated_date <- date((parse_date_time(s_Addison___OHare$date,"mdy")))
s_Addison___OHare$the_year <- year(s_Addison___OHare$updated_date)
s_Addison___OHare$the_month <- month(s_Addison___OHare$updated_date,abbr = TRUE, label = TRUE)
s_Addison___OHare$weekday <- wday(s_Addison___OHare$updated_date, abbr = TRUE, label = TRUE)
s_Pulaski___Orange$updated_date <- date((parse_date_time(s_Pulaski___Orange$date,"mdy")))
s_Pulaski___Orange$the_year <- year(s_Pulaski___Orange$updated_date)
s_Pulaski___Orange$the_month <- month(s_Pulaski___Orange$updated_date,abbr = TRUE, label = TRUE)
s_Pulaski___Orange$weekday <- wday(s_Pulaski___Orange$updated_date, abbr = TRUE, label = TRUE)
s_Noyes$updated_date <- date((parse_date_time(s_Noyes$date,"mdy")))
s_Noyes$the_year <- year(s_Noyes$updated_date)
s_Noyes$the_month <- month(s_Noyes$updated_date,abbr = TRUE, label = TRUE)
s_Noyes$weekday <- wday(s_Noyes$updated_date, abbr = TRUE, label = TRUE)
s_47th___South_Elevated$updated_date <- date((parse_date_time(s_47th___South_Elevated$date,"mdy")))
s_47th___South_Elevated$the_year <- year(s_47th___South_Elevated$updated_date)
s_47th___South_Elevated$the_month <- month(s_47th___South_Elevated$updated_date,abbr = TRUE, label = TRUE)
s_47th___South_Elevated$weekday <- wday(s_47th___South_Elevated$updated_date, abbr = TRUE, label = TRUE)
s_Merchandise_Mart$updated_date <- date((parse_date_time(s_Merchandise_Mart$date,"mdy")))
s_Merchandise_Mart$the_year <- year(s_Merchandise_Mart$updated_date)
s_Merchandise_Mart$the_month <- month(s_Merchandise_Mart$updated_date,abbr = TRUE, label = TRUE)
s_Merchandise_Mart$weekday <- wday(s_Merchandise_Mart$updated_date, abbr = TRUE, label = TRUE)
s_Midway_Airport$updated_date <- date((parse_date_time(s_Midway_Airport$date,"mdy")))
s_Midway_Airport$the_year <- year(s_Midway_Airport$updated_date)
s_Midway_Airport$the_month <- month(s_Midway_Airport$updated_date,abbr = TRUE, label = TRUE)
s_Midway_Airport$weekday <- wday(s_Midway_Airport$updated_date, abbr = TRUE, label = TRUE)
s_43rd$updated_date <- date((parse_date_time(s_43rd$date,"mdy")))
s_43rd$the_year <- year(s_43rd$updated_date)
s_43rd$the_month <- month(s_43rd$updated_date,abbr = TRUE, label = TRUE)
s_43rd$weekday <- wday(s_43rd$updated_date, abbr = TRUE, label = TRUE)
s_Western__Milwaukee$updated_date <- date((parse_date_time(s_Western__Milwaukee$date,"mdy")))
s_Western__Milwaukee$the_year <- year(s_Western__Milwaukee$updated_date)
s_Western__Milwaukee$the_month <- month(s_Western__Milwaukee$updated_date,abbr = TRUE, label = TRUE)
s_Western__Milwaukee$weekday <- wday(s_Western__Milwaukee$updated_date, abbr = TRUE, label = TRUE)
s_Ashland___Lake$updated_date <- date((parse_date_time(s_Ashland___Lake$date,"mdy")))
s_Ashland___Lake$the_year <- year(s_Ashland___Lake$updated_date)
s_Ashland___Lake$the_month <- month(s_Ashland___Lake$updated_date,abbr = TRUE, label = TRUE)
s_Ashland___Lake$weekday <- wday(s_Ashland___Lake$updated_date, abbr = TRUE, label = TRUE)
s_Belmont___OHare$updated_date <- date((parse_date_time(s_Belmont___OHare$date,"mdy")))
s_Belmont___OHare$the_year <- year(s_Belmont___OHare$updated_date)
s_Belmont___OHare$the_month <- month(s_Belmont___OHare$updated_date,abbr = TRUE, label = TRUE)
s_Belmont___OHare$weekday <- wday(s_Belmont___OHare$updated_date, abbr = TRUE, label = TRUE)
s_Oak_Park___Lake$updated_date <- date((parse_date_time(s_Oak_Park___Lake$date,"mdy")))
s_Oak_Park___Lake$the_year <- year(s_Oak_Park___Lake$updated_date)
s_Oak_Park___Lake$the_month <- month(s_Oak_Park___Lake$updated_date,abbr = TRUE, label = TRUE)
s_Oak_Park___Lake$weekday <- wday(s_Oak_Park___Lake$updated_date, abbr = TRUE, label = TRUE)
s_Conservatory$updated_date <- date((parse_date_time(s_Conservatory$date,"mdy")))
s_Conservatory$the_year <- year(s_Conservatory$updated_date)
s_Conservatory$the_month <- month(s_Conservatory$updated_date,abbr = TRUE, label = TRUE)
s_Conservatory$weekday <- wday(s_Conservatory$updated_date, abbr = TRUE, label = TRUE)
s_Library$updated_date <- date((parse_date_time(s_Library$date,"mdy")))
s_Library$the_year <- year(s_Library$updated_date)
s_Library$the_month <- month(s_Library$updated_date,abbr = TRUE, label = TRUE)
s_Library$weekday <- wday(s_Library$updated_date, abbr = TRUE, label = TRUE)
s_Loyola$updated_date <- date((parse_date_time(s_Loyola$date,"mdy")))
s_Loyola$the_year <- year(s_Loyola$updated_date)
s_Loyola$the_month <- month(s_Loyola$updated_date,abbr = TRUE, label = TRUE)
s_Loyola$weekday <- wday(s_Loyola$updated_date, abbr = TRUE, label = TRUE)
s_Southport$updated_date <- date((parse_date_time(s_Southport$date,"mdy")))
s_Southport$the_year <- year(s_Southport$updated_date)
s_Southport$the_month <- month(s_Southport$updated_date,abbr = TRUE, label = TRUE)
s_Southport$weekday <- wday(s_Southport$updated_date, abbr = TRUE, label = TRUE)
s_Montrose___OHare$updated_date <- date((parse_date_time(s_Montrose___OHare$date,"mdy")))
s_Montrose___OHare$the_year <- year(s_Montrose___OHare$updated_date)
s_Montrose___OHare$the_month <- month(s_Montrose___OHare$updated_date,abbr = TRUE, label = TRUE)
s_Montrose___OHare$weekday <- wday(s_Montrose___OHare$updated_date, abbr = TRUE, label = TRUE)
s_Jarvis$updated_date <- date((parse_date_time(s_Jarvis$date,"mdy")))
s_Jarvis$the_year <- year(s_Jarvis$updated_date)
s_Jarvis$the_month <- month(s_Jarvis$updated_date,abbr = TRUE, label = TRUE)
s_Jarvis$weekday <- wday(s_Jarvis$updated_date, abbr = TRUE, label = TRUE)
s_South_Boulevard$updated_date <- date((parse_date_time(s_South_Boulevard$date,"mdy")))
s_South_Boulevard$the_year <- year(s_South_Boulevard$updated_date)
s_South_Boulevard$the_month <- month(s_South_Boulevard$updated_date,abbr = TRUE, label = TRUE)
s_South_Boulevard$weekday <- wday(s_South_Boulevard$updated_date, abbr = TRUE, label = TRUE)
s_Cicero___Forest_Park$updated_date <- date((parse_date_time(s_Cicero___Forest_Park$date,"mdy")))
s_Cicero___Forest_Park$the_year <- year(s_Cicero___Forest_Park$updated_date)
s_Cicero___Forest_Park$the_month <- month(s_Cicero___Forest_Park$updated_date,abbr = TRUE, label = TRUE)
s_Cicero___Forest_Park$weekday <- wday(s_Cicero___Forest_Park$updated_date, abbr = TRUE, label = TRUE)
s_Medical_Center$updated_date <- date((parse_date_time(s_Medical_Center$date,"mdy")))
s_Medical_Center$the_year <- year(s_Medical_Center$updated_date)
s_Medical_Center$the_month <- month(s_Medical_Center$updated_date,abbr = TRUE, label = TRUE)
s_Medical_Center$weekday <- wday(s_Medical_Center$updated_date, abbr = TRUE, label = TRUE)
s_Davis$updated_date <- date((parse_date_time(s_Davis$date,"mdy")))
s_Davis$the_year <- year(s_Davis$updated_date)
s_Davis$the_month <- month(s_Davis$updated_date,abbr = TRUE, label = TRUE)
s_Davis$weekday <- wday(s_Davis$updated_date, abbr = TRUE, label = TRUE)
s_Clark__Division$updated_date <- date((parse_date_time(s_Clark__Division$date,"mdy")))
s_Clark__Division$the_year <- year(s_Clark__Division$updated_date)
s_Clark__Division$the_month <- month(s_Clark__Division$updated_date,abbr = TRUE, label = TRUE)
s_Clark__Division$weekday <- wday(s_Clark__Division$updated_date, abbr = TRUE, label = TRUE)
s_Jackson__Dearborn$updated_date <- date((parse_date_time(s_Jackson__Dearborn$date,"mdy")))
s_Jackson__Dearborn$the_year <- year(s_Jackson__Dearborn$updated_date)
s_Jackson__Dearborn$the_month <- month(s_Jackson__Dearborn$updated_date,abbr = TRUE, label = TRUE)
s_Jackson__Dearborn$weekday <- wday(s_Jackson__Dearborn$updated_date, abbr = TRUE, label = TRUE)
s_Washington__Wabash$updated_date <- date((parse_date_time(s_Washington__Wabash$date,"mdy")))
s_Washington__Wabash$the_year <- year(s_Washington__Wabash$updated_date)
s_Washington__Wabash$the_month <- month(s_Washington__Wabash$updated_date,abbr = TRUE, label = TRUE)
s_Washington__Wabash$weekday <- wday(s_Washington__Wabash$updated_date, abbr = TRUE, label = TRUE)
s_Francisco$updated_date <- date((parse_date_time(s_Francisco$date,"mdy")))
s_Francisco$the_year <- year(s_Francisco$updated_date)
s_Francisco$the_month <- month(s_Francisco$updated_date,abbr = TRUE, label = TRUE)
s_Francisco$weekday <- wday(s_Francisco$updated_date, abbr = TRUE, label = TRUE)
s_Central___Evanston$updated_date <- date((parse_date_time(s_Central___Evanston$date,"mdy")))
s_Central___Evanston$the_year <- year(s_Central___Evanston$updated_date)
s_Central___Evanston$the_month <- month(s_Central___Evanston$updated_date,abbr = TRUE, label = TRUE)
s_Central___Evanston$weekday <- wday(s_Central___Evanston$updated_date, abbr = TRUE, label = TRUE)
s_Oakton___Skokie$updated_date <- date((parse_date_time(s_Oakton___Skokie$date,"mdy")))
s_Oakton___Skokie$the_year <- year(s_Oakton___Skokie$updated_date)
s_Oakton___Skokie$the_month <- month(s_Oakton___Skokie$updated_date,abbr = TRUE, label = TRUE)
s_Oakton___Skokie$weekday <- wday(s_Oakton___Skokie$updated_date, abbr = TRUE, label = TRUE)
s_Austin___Lake$updated_date <- date((parse_date_time(s_Austin___Lake$date,"mdy")))
s_Austin___Lake$the_year <- year(s_Austin___Lake$updated_date)
s_Austin___Lake$the_month <- month(s_Austin___Lake$updated_date,abbr = TRUE, label = TRUE)
s_Austin___Lake$weekday <- wday(s_Austin___Lake$updated_date, abbr = TRUE, label = TRUE)
s_Bryn_Mawr$updated_date <- date((parse_date_time(s_Bryn_Mawr$date,"mdy")))
s_Bryn_Mawr$the_year <- year(s_Bryn_Mawr$updated_date)
s_Bryn_Mawr$the_month <- month(s_Bryn_Mawr$updated_date,abbr = TRUE, label = TRUE)
s_Bryn_Mawr$weekday <- wday(s_Bryn_Mawr$updated_date, abbr = TRUE, label = TRUE)
s_Kostner$updated_date <- date((parse_date_time(s_Kostner$date,"mdy")))
s_Kostner$the_year <- year(s_Kostner$updated_date)
s_Kostner$the_month <- month(s_Kostner$updated_date,abbr = TRUE, label = TRUE)
s_Kostner$weekday <- wday(s_Kostner$updated_date, abbr = TRUE, label = TRUE)
s_Forest_Park$updated_date <- date((parse_date_time(s_Forest_Park$date,"mdy")))
s_Forest_Park$the_year <- year(s_Forest_Park$updated_date)
s_Forest_Park$the_month <- month(s_Forest_Park$updated_date,abbr = TRUE, label = TRUE)
s_Forest_Park$weekday <- wday(s_Forest_Park$updated_date, abbr = TRUE, label = TRUE)
s_California___Lake$updated_date <- date((parse_date_time(s_California___Lake$date,"mdy")))
s_California___Lake$the_year <- year(s_California___Lake$updated_date)
s_California___Lake$the_month <- month(s_California___Lake$updated_date,abbr = TRUE, label = TRUE)
s_California___Lake$weekday <- wday(s_California___Lake$updated_date, abbr = TRUE, label = TRUE)
s_Garfield___South_Elevated$updated_date <- date((parse_date_time(s_Garfield___South_Elevated$date,"mdy")))
s_Garfield___South_Elevated$the_year <- year(s_Garfield___South_Elevated$updated_date)
s_Garfield___South_Elevated$the_month <- month(s_Garfield___South_Elevated$updated_date,abbr = TRUE, label = TRUE)
s_Garfield___South_Elevated$weekday <- wday(s_Garfield___South_Elevated$updated_date, abbr = TRUE, label = TRUE)
s_Rockwell$updated_date <- date((parse_date_time(s_Rockwell$date,"mdy")))
s_Rockwell$the_year <- year(s_Rockwell$updated_date)
s_Rockwell$the_month <- month(s_Rockwell$updated_date,abbr = TRUE, label = TRUE)
s_Rockwell$weekday <- wday(s_Rockwell$updated_date, abbr = TRUE, label = TRUE)
s_Diversey$updated_date <- date((parse_date_time(s_Diversey$date,"mdy")))
s_Diversey$the_year <- year(s_Diversey$updated_date)
s_Diversey$the_month <- month(s_Diversey$updated_date,abbr = TRUE, label = TRUE)
s_Diversey$weekday <- wday(s_Diversey$updated_date, abbr = TRUE, label = TRUE)
s_Argyle$updated_date <- date((parse_date_time(s_Argyle$date,"mdy")))
s_Argyle$the_year <- year(s_Argyle$updated_date)
s_Argyle$the_month <- month(s_Argyle$updated_date,abbr = TRUE, label = TRUE)
s_Argyle$weekday <- wday(s_Argyle$updated_date, abbr = TRUE, label = TRUE)
s_LaSalle$updated_date <- date((parse_date_time(s_LaSalle$date,"mdy")))
s_LaSalle$the_year <- year(s_LaSalle$updated_date)
s_LaSalle$the_month <- month(s_LaSalle$updated_date,abbr = TRUE, label = TRUE)
s_LaSalle$weekday <- wday(s_LaSalle$updated_date, abbr = TRUE, label = TRUE)
s_Monroe__Dearborn$updated_date <- date((parse_date_time(s_Monroe__Dearborn$date,"mdy")))
s_Monroe__Dearborn$the_year <- year(s_Monroe__Dearborn$updated_date)
s_Monroe__Dearborn$the_month <- month(s_Monroe__Dearborn$updated_date,abbr = TRUE, label = TRUE)
s_Monroe__Dearborn$weekday <- wday(s_Monroe__Dearborn$updated_date, abbr = TRUE, label = TRUE)
s_Rosemont$updated_date <- date((parse_date_time(s_Rosemont$date,"mdy")))
s_Rosemont$the_year <- year(s_Rosemont$updated_date)
s_Rosemont$the_month <- month(s_Rosemont$updated_date,abbr = TRUE, label = TRUE)
s_Rosemont$weekday <- wday(s_Rosemont$updated_date, abbr = TRUE, label = TRUE)
s_King_Drive$updated_date <- date((parse_date_time(s_King_Drive$date,"mdy")))
s_King_Drive$the_year <- year(s_King_Drive$updated_date)
s_King_Drive$the_month <- month(s_King_Drive$updated_date,abbr = TRUE, label = TRUE)
s_King_Drive$weekday <- wday(s_King_Drive$updated_date, abbr = TRUE, label = TRUE)
s_Armitage$updated_date <- date((parse_date_time(s_Armitage$date,"mdy")))
s_Armitage$the_year <- year(s_Armitage$updated_date)
s_Armitage$the_month <- month(s_Armitage$updated_date,abbr = TRUE, label = TRUE)
s_Armitage$weekday <- wday(s_Armitage$updated_date, abbr = TRUE, label = TRUE)
s_Thorndale$updated_date <- date((parse_date_time(s_Thorndale$date,"mdy")))
s_Thorndale$the_year <- year(s_Thorndale$updated_date)
s_Thorndale$the_month <- month(s_Thorndale$updated_date,abbr = TRUE, label = TRUE)
s_Thorndale$weekday <- wday(s_Thorndale$updated_date, abbr = TRUE, label = TRUE)
s_Western___Brown$updated_date <- date((parse_date_time(s_Western___Brown$date,"mdy")))
s_Western___Brown$the_year <- year(s_Western___Brown$updated_date)
s_Western___Brown$the_month <- month(s_Western___Brown$updated_date,abbr = TRUE, label = TRUE)
s_Western___Brown$weekday <- wday(s_Western___Brown$updated_date, abbr = TRUE, label = TRUE)
s_Skokie$updated_date <- date((parse_date_time(s_Skokie$date,"mdy")))
s_Skokie$the_year <- year(s_Skokie$updated_date)
s_Skokie$the_month <- month(s_Skokie$updated_date,abbr = TRUE, label = TRUE)
s_Skokie$weekday <- wday(s_Skokie$updated_date, abbr = TRUE, label = TRUE)
s_Washington__State$updated_date <- date((parse_date_time(s_Washington__State$date,"mdy")))
s_Washington__State$the_year <- year(s_Washington__State$updated_date)
s_Washington__State$the_month <- month(s_Washington__State$updated_date,abbr = TRUE, label = TRUE)
s_Washington__State$weekday <- wday(s_Washington__State$updated_date, abbr = TRUE, label = TRUE)
s_Homan$updated_date <- date((parse_date_time(s_Homan$date,"mdy")))
s_Homan$the_year <- year(s_Homan$updated_date)
s_Homan$the_month <- month(s_Homan$updated_date,abbr = TRUE, label = TRUE)
s_Homan$weekday <- wday(s_Homan$updated_date, abbr = TRUE, label = TRUE)
# 
# save(s_Jefferson_Park,s_Cermak___Chinatown,s_Central___Lake,s_Dempster___Skokie,s_Dempster,s_Lake__State,s_Oak_Park___Forest_Park,s_Kedzie___Homan___Forest_Park,s_35th__Archer,s_Addison___North_Main,s_Main,s_Chicago__State,s_Wellington,s_Austin___Forest_Park,s_Clinton___Lake,s_East_63rd___Cottage_Grove,s_Grand__State,s_Wilson,s_Cicero___Cermak,s_State__Lake,s_51st,s_95th__Dan_Ryan,s_Jackson__State,s_Randolph__Wabash,s_Logan_Square,s_Morse,s_Grand__Milwaukee,s_69th,s_Paulina,s_Damen___Brown,s_Washington__Dearborn,s_Kimball,s_Clark__Lake,s_Lawrence,s_Polk,s_47th___Dan_Ryan,s_Sedgwick,s_54th__Cermak,s_Ashland__63rd,s_Morgan___Lake,s_Harrison,s_Sheridan,s_Racine,s_Washington__Wells,s_Quincy__Wells,s_Foster,s_California__Milwaukee,s_Cermak___McCormick_Place,s_Sox___35th___Dan_Ryan,s_Chicago__Milwaukee,s_OHare_Airport,s_Kedzie___Lake,s_Fullerton,s_Irving_Park___Brown,s_LaSalle__Van_Buren,s_Belmont___North_Main,s_79th,s_Adams__Wabash,s_Western___Orange,s_Clinton___Forest_Park,s_UIC___Halsted,s_35___Bronzeville___IIT,s_87th,s_18th,s_Indiana,s_Monroe__State,s_Irving_Park___OHare,s_Cumberland,s_Roosevelt,s_Damen__Milwaukee,s_Kedzie___Midway,s_63rd___Dan_Ryan,s_Kedzie___Cermak,s_Addison___Brown,s_Division__Milwaukee,s_Damen___Cermak,s_Cicero___Lake,s_Madison__Wabash,s_Harlem___Lake,s_Pulaski___Cermak,s_Kedzie___Brown,s_Central_Park,s_Harlem___OHare,s_Chicago__Franklin,s_North__Clybourn,s_Berwyn,s_Laramie,s_Howard,s_Granville,s_Western___Forest_Park,s_California___Cermak,s_Ridgeland,s_Western___Cermak,s_Halsted__63rd,s_Pulaski___Forest_Park,s_Montrose___Brown,s_Linden,s_Pulaski___Lake,s_Harlem___Forest_Park,s_Ashland___Orange,s_Garfield___Dan_Ryan,s_Halsted___Orange,s_Addison___OHare,s_Pulaski___Orange,s_Noyes,s_47th___South_Elevated,s_Merchandise_Mart,s_Midway_Airport,s_43rd,s_Western__Milwaukee,s_Ashland___Lake,s_Belmont___OHare,s_Oak_Park___Lake,s_Conservatory,s_Library,s_Loyola,s_Southport,s_Montrose___OHare,s_Jarvis,s_South_Boulevard,s_Cicero___Forest_Park,s_Medical_Center,s_Davis,s_Clark__Division,s_Jackson__Dearborn,s_Washington__Wabash,s_Francisco,s_Central___Evanston,s_Oakton___Skokie,s_Austin___Lake,s_Bryn_Mawr,s_Kostner,s_Forest_Park,s_California___Lake,s_Garfield___South_Elevated,s_Rockwell,s_Diversey,s_Argyle,s_LaSalle,s_Monroe__Dearborn,s_Rosemont,s_King_Drive,s_Armitage,s_Thorndale,s_Western___Brown,s_Skokie,s_Washington__State,s_Homan,file = "rdata/data2.RData")
# load(file = "rdata/data2.RData")
# dfMerge <- do.call("rbind", list(s_Jefferson_Park,s_Cermak___Chinatown,s_Central___Lake,s_Dempster___Skokie,s_Dempster,s_Lake__State,s_Oak_Park___Forest_Park,s_Kedzie___Homan___Forest_Park,s_35th__Archer,s_Addison___North_Main,s_Main,s_Chicago__State,s_Wellington,s_Austin___Forest_Park,s_Clinton___Lake,s_East_63rd___Cottage_Grove,s_Grand__State,s_Wilson,s_Cicero___Cermak,s_State__Lake,s_51st,s_95th__Dan_Ryan,s_Jackson__State,s_Randolph__Wabash,s_Logan_Square,s_Morse,s_Grand__Milwaukee,s_69th,s_Paulina,s_Damen___Brown,s_Washington__Dearborn,s_Kimball,s_Clark__Lake,s_Lawrence,s_Polk,s_47th___Dan_Ryan,s_Sedgwick,s_54th__Cermak,s_Ashland__63rd,s_Morgan___Lake,s_Harrison,s_Sheridan,s_Racine,s_Washington__Wells,s_Quincy__Wells,s_Foster,s_California__Milwaukee,s_Cermak___McCormick_Place,s_Sox___35th___Dan_Ryan,s_Chicago__Milwaukee,s_OHare_Airport,s_Kedzie___Lake,s_Fullerton,s_Irving_Park___Brown,s_LaSalle__Van_Buren,s_Belmont___North_Main,s_79th,s_Adams__Wabash,s_Western___Orange,s_Clinton___Forest_Park,s_UIC___Halsted,s_35___Bronzeville___IIT,s_87th,s_18th,s_Indiana,s_Monroe__State,s_Irving_Park___OHare,s_Cumberland,s_Roosevelt,s_Damen__Milwaukee,s_Kedzie___Midway,s_63rd___Dan_Ryan,s_Kedzie___Cermak,s_Addison___Brown,s_Division__Milwaukee,s_Damen___Cermak,s_Cicero___Lake,s_Madison__Wabash,s_Harlem___Lake,s_Pulaski___Cermak,s_Kedzie___Brown,s_Central_Park,s_Harlem___OHare,s_Chicago__Franklin,s_North__Clybourn,s_Berwyn,s_Laramie,s_Howard,s_Granville,s_Western___Forest_Park,s_California___Cermak,s_Ridgeland,s_Western___Cermak,s_Halsted__63rd,s_Pulaski___Forest_Park,s_Montrose___Brown,s_Linden,s_Pulaski___Lake,s_Harlem___Forest_Park,s_Ashland___Orange,s_Garfield___Dan_Ryan,s_Halsted___Orange,s_Addison___OHare,s_Pulaski___Orange,s_Noyes,s_47th___South_Elevated,s_Merchandise_Mart,s_Midway_Airport,s_43rd,s_Western__Milwaukee,s_Ashland___Lake,s_Belmont___OHare,s_Oak_Park___Lake,s_Conservatory,s_Library,s_Loyola,s_Southport,s_Montrose___OHare,s_Jarvis,s_South_Boulevard,s_Cicero___Forest_Park,s_Medical_Center,s_Davis,s_Clark__Division,s_Jackson__Dearborn,s_Washington__Wabash,s_Francisco,s_Central___Evanston,s_Oakton___Skokie,s_Austin___Lake,s_Bryn_Mawr,s_Kostner,s_Forest_Park,s_California___Lake,s_Garfield___South_Elevated,s_Rockwell,s_Diversey,s_Argyle,s_LaSalle,s_Monroe__Dearborn,s_Rosemont,s_King_Drive,s_Armitage,s_Thorndale,s_Western___Brown,s_Skokie,s_Washington__State,s_Homan))
# df <- subset(dfMerge, updated_date == "2021-8-23")
# August 23, 2021
# 2021-08-23

saveRDS(s_Jefferson_Park,file = "rdata/Jefferson_Park.rds")
saveRDS(s_Cermak___Chinatown,file = "rdata/Cermak-Chinatown.rds")
saveRDS(s_Central___Lake,file = "rdata/Central-Lake.rds")
saveRDS(s_Dempster___Skokie,file = "rdata/Dempster-Skokie.rds")
saveRDS(s_Dempster,file = "rdata/Dempster.rds")
saveRDS(s_Lake__State,file = "rdata/Lake__State.rds")
saveRDS(s_Oak_Park___Forest_Park,file = "rdata/Oak_Park-Forest_Park.rds")
saveRDS(s_Kedzie___Homan___Forest_Park,file = "rdata/Kedzie-Homan-Forest_Park.rds")
saveRDS(s_35th__Archer,file = "rdata/35th__Archer.rds")
saveRDS(s_Addison___North_Main,file = "rdata/Addison-North_Main.rds")
saveRDS(s_Main,file = "rdata/Main.rds")
saveRDS(s_Chicago__State,file = "rdata/Chicago__State.rds")
saveRDS(s_Wellington,file = "rdata/Wellington.rds")
saveRDS(s_Austin___Forest_Park,file = "rdata/Austin-Forest_Park.rds")
saveRDS(s_Clinton___Lake,file = "rdata/Clinton-Lake.rds")
saveRDS(s_East_63rd___Cottage_Grove,file = "rdata/East_63rd-Cottage_Grove.rds")
saveRDS(s_Grand__State,file = "rdata/Grand__State.rds")
saveRDS(s_Wilson,file = "rdata/Wilson.rds")
saveRDS(s_Cicero___Cermak,file = "rdata/Cicero-Cermak.rds")
saveRDS(s_State__Lake,file = "rdata/State__Lake.rds")
saveRDS(s_51st,file = "rdata/51st.rds")
saveRDS(s_95th__Dan_Ryan,file = "rdata/95th__Dan_Ryan.rds")
saveRDS(s_Jackson__State,file = "rdata/Jackson__State.rds")
saveRDS(s_Randolph__Wabash,file = "rdata/Randolph__Wabash.rds")
saveRDS(s_Logan_Square,file = "rdata/Logan_Square.rds")
saveRDS(s_Morse,file = "rdata/Morse.rds")
saveRDS(s_Grand__Milwaukee,file = "rdata/Grand__Milwaukee.rds")
saveRDS(s_69th,file = "rdata/69th.rds")
saveRDS(s_Paulina,file = "rdata/Paulina.rds")
saveRDS(s_Damen___Brown,file = "rdata/Damen-Brown.rds")
saveRDS(s_Washington__Dearborn,file = "rdata/Washington__Dearborn.rds")
saveRDS(s_Kimball,file = "rdata/Kimball.rds")
saveRDS(s_Clark__Lake,file = "rdata/Clark__Lake.rds")
saveRDS(s_Lawrence,file = "rdata/Lawrence.rds")
saveRDS(s_Polk,file = "rdata/Polk.rds")
saveRDS(s_47th___Dan_Ryan,file = "rdata/47th-Dan_Ryan.rds")
saveRDS(s_Sedgwick,file = "rdata/Sedgwick.rds")
saveRDS(s_54th__Cermak,file = "rdata/54th__Cermak.rds")
saveRDS(s_Ashland__63rd,file = "rdata/Ashland__63rd.rds")
saveRDS(s_Morgan___Lake,file = "rdata/Morgan-Lake.rds")
saveRDS(s_Harrison,file = "rdata/Harrison.rds")
saveRDS(s_Sheridan,file = "rdata/Sheridan.rds")
saveRDS(s_Racine,file = "rdata/Racine.rds")
saveRDS(s_Washington__Wells,file = "rdata/Washington__Wells.rds")
saveRDS(s_Quincy__Wells,file = "rdata/Quincy__Wells.rds")
saveRDS(s_Foster,file = "rdata/Foster.rds")
saveRDS(s_California__Milwaukee,file = "rdata/California__Milwaukee.rds")
saveRDS(s_Cermak___McCormick_Place,file = "rdata/Cermak-McCormick_Place.rds")
saveRDS(s_Sox___35th___Dan_Ryan,file = "rdata/Sox-35th-Dan_Ryan.rds")
saveRDS(s_Chicago__Milwaukee,file = "rdata/Chicago__Milwaukee.rds")
saveRDS(s_OHare_Airport,file = "rdata/O'Hare_Airport.rds")
saveRDS(s_Kedzie___Lake,file = "rdata/Kedzie-Lake.rds")
saveRDS(s_Fullerton,file = "rdata/Fullerton.rds")
saveRDS(s_Irving_Park___Brown,file = "rdata/Irving_Park-Brown.rds")
saveRDS(s_LaSalle__Van_Buren,file = "rdata/LaSalle__Van_Buren.rds")
saveRDS(s_Belmont___North_Main,file = "rdata/Belmont-North_Main.rds")
saveRDS(s_79th,file = "rdata/79th.rds")
saveRDS(s_Adams__Wabash,file = "rdata/Adams__Wabash.rds")
saveRDS(s_Western___Orange,file = "rdata/Western-Orange.rds")
saveRDS(s_Clinton___Forest_Park,file = "rdata/Clinton-Forest_Park.rds")
saveRDS(s_UIC___Halsted,file = "rdata/UIC-Halsted.rds")
saveRDS(s_35___Bronzeville___IIT,file = "rdata/35-Bronzeville-IIT.rds")
saveRDS(s_87th,file = "rdata/87th.rds")
saveRDS(s_18th,file = "rdata/18th.rds")
saveRDS(s_Indiana,file = "rdata/Indiana.rds")
saveRDS(s_Monroe__State,file = "rdata/Monroe__State.rds")
saveRDS(s_Irving_Park___OHare,file = "rdata/Irving_Park-O'Hare.rds")
saveRDS(s_Cumberland,file = "rdata/Cumberland.rds")
saveRDS(s_Roosevelt,file = "rdata/Roosevelt.rds")
saveRDS(s_Damen__Milwaukee,file = "rdata/Damen__Milwaukee.rds")
saveRDS(s_Kedzie___Midway,file = "rdata/Kedzie-Midway.rds")
saveRDS(s_63rd___Dan_Ryan,file = "rdata/63rd-Dan_Ryan.rds")
saveRDS(s_Kedzie___Cermak,file = "rdata/Kedzie-Cermak.rds")
saveRDS(s_Addison___Brown,file = "rdata/Addison-Brown.rds")
saveRDS(s_Division__Milwaukee,file = "rdata/Division__Milwaukee.rds")
saveRDS(s_Damen___Cermak,file = "rdata/Damen-Cermak.rds")
saveRDS(s_Cicero___Lake,file = "rdata/Cicero-Lake.rds")
saveRDS(s_Madison__Wabash,file = "rdata/Madison__Wabash.rds")
saveRDS(s_Harlem___Lake,file = "rdata/Harlem-Lake.rds")
saveRDS(s_Pulaski___Cermak,file = "rdata/Pulaski-Cermak.rds")
saveRDS(s_Kedzie___Brown,file = "rdata/Kedzie-Brown.rds")
saveRDS(s_Central_Park,file = "rdata/Central_Park.rds")
saveRDS(s_Harlem___OHare,file = "rdata/Harlem-O'Hare.rds")
saveRDS(s_Chicago__Franklin,file = "rdata/Chicago__Franklin.rds")
saveRDS(s_North__Clybourn,file = "rdata/North__Clybourn.rds")
saveRDS(s_Berwyn,file = "rdata/Berwyn.rds")
saveRDS(s_Laramie,file = "rdata/Laramie.rds")
saveRDS(s_Howard,file = "rdata/Howard.rds")
saveRDS(s_Granville,file = "rdata/Granville.rds")
saveRDS(s_Western___Forest_Park,file = "rdata/Western-Forest_Park.rds")
saveRDS(s_California___Cermak,file = "rdata/California-Cermak.rds")
saveRDS(s_Ridgeland,file = "rdata/Ridgeland.rds")
saveRDS(s_Western___Cermak,file = "rdata/Western-Cermak.rds")
saveRDS(s_Halsted__63rd,file = "rdata/Halsted__63rd.rds")
saveRDS(s_Pulaski___Forest_Park,file = "rdata/Pulaski-Forest_Park.rds")
saveRDS(s_Montrose___Brown,file = "rdata/Montrose-Brown.rds")
saveRDS(s_Linden,file = "rdata/Linden.rds")
saveRDS(s_Pulaski___Lake,file = "rdata/Pulaski-Lake.rds")
saveRDS(s_Harlem___Forest_Park,file = "rdata/Harlem-Forest_Park.rds")
saveRDS(s_Ashland___Orange,file = "rdata/Ashland-Orange.rds")
saveRDS(s_Garfield___Dan_Ryan,file = "rdata/Garfield-Dan_Ryan.rds")
saveRDS(s_Halsted___Orange,file = "rdata/Halsted-Orange.rds")
saveRDS(s_Addison___OHare,file = "rdata/Addison-O'Hare.rds")
saveRDS(s_Pulaski___Orange,file = "rdata/Pulaski-Orange.rds")
saveRDS(s_Noyes,file = "rdata/Noyes.rds")
saveRDS(s_47th___South_Elevated,file = "rdata/47th-South_Elevated.rds")
saveRDS(s_Merchandise_Mart,file = "rdata/Merchandise_Mart.rds")
saveRDS(s_Midway_Airport,file = "rdata/Midway_Airport.rds")
saveRDS(s_43rd,file = "rdata/43rd.rds")
saveRDS(s_Western__Milwaukee,file = "rdata/Western__Milwaukee.rds")
saveRDS(s_Ashland___Lake,file = "rdata/Ashland-Lake.rds")
saveRDS(s_Belmont___OHare,file = "rdata/Belmont-O'Hare.rds")
saveRDS(s_Oak_Park___Lake,file = "rdata/Oak_Park-Lake.rds")
saveRDS(s_Conservatory,file = "rdata/Conservatory.rds")
saveRDS(s_Library,file = "rdata/Library.rds")
saveRDS(s_Loyola,file = "rdata/Loyola.rds")
saveRDS(s_Southport,file = "rdata/Southport.rds")
saveRDS(s_Montrose___OHare,file = "rdata/Montrose-O'Hare.rds")
saveRDS(s_Jarvis,file = "rdata/Jarvis.rds")
saveRDS(s_South_Boulevard,file = "rdata/South_Boulevard.rds")
saveRDS(s_Cicero___Forest_Park,file = "rdata/Cicero-Forest_Park.rds")
saveRDS(s_Medical_Center,file = "rdata/Medical_Center.rds")
saveRDS(s_Davis,file = "rdata/Davis.rds")
saveRDS(s_Clark__Division,file = "rdata/Clark__Division.rds")
saveRDS(s_Jackson__Dearborn,file = "rdata/Jackson__Dearborn.rds")
saveRDS(s_Washington__Wabash,file = "rdata/Washington__Wabash.rds")
saveRDS(s_Francisco,file = "rdata/Francisco.rds")
saveRDS(s_Central___Evanston,file = "rdata/Central-Evanston.rds")
saveRDS(s_Oakton___Skokie,file = "rdata/Oakton-Skokie.rds")
saveRDS(s_Austin___Lake,file = "rdata/Austin-Lake.rds")
saveRDS(s_Bryn_Mawr,file = "rdata/Bryn_Mawr.rds")
saveRDS(s_Kostner,file = "rdata/Kostner.rds")
saveRDS(s_Forest_Park,file = "rdata/Forest_Park.rds")
saveRDS(s_California___Lake,file = "rdata/California-Lake.rds")
saveRDS(s_Garfield___South_Elevated,file = "rdata/Garfield-South_Elevated.rds")
saveRDS(s_Rockwell,file = "rdata/Rockwell.rds")
saveRDS(s_Diversey,file = "rdata/Diversey.rds")
saveRDS(s_Argyle,file = "rdata/Argyle.rds")
saveRDS(s_LaSalle,file = "rdata/LaSalle.rds")
saveRDS(s_Monroe__Dearborn,file = "rdata/Monroe__Dearborn.rds")
saveRDS(s_Rosemont,file = "rdata/Rosemont.rds")
saveRDS(s_King_Drive,file = "rdata/King_Drive.rds")
saveRDS(s_Armitage,file = "rdata/Armitage.rds")
saveRDS(s_Thorndale,file = "rdata/Thorndale.rds")
saveRDS(s_Western___Brown,file = "rdata/Western-Brown.rds")
saveRDS(s_Skokie,file = "rdata/Skokie.rds")
saveRDS(s_Washington__State,file = "rdata/Washington__State.rds")
saveRDS(s_Homan,file = "rdata/Homan.rds")




s_Jefferson_Park <- readRDS(file = "rdata/Jefferson_Park.rds")
s_Cermak___Chinatown <- readRDS(file = "rdata/Cermak-Chinatown.rds")
s_Central___Lake <- readRDS(file = "rdata/Central-Lake.rds")
s_Dempster___Skokie <- readRDS(file = "rdata/Dempster-Skokie.rds")
s_Dempster <- readRDS(file = "rdata/Dempster.rds")
s_Lake__State <- readRDS(file = "rdata/Lake__State.rds")
s_Oak_Park___Forest_Park <- readRDS(file = "rdata/Oak_Park-Forest_Park.rds")
s_Kedzie___Homan___Forest_Park <- readRDS(file = "rdata/Kedzie-Homan-Forest_Park.rds")
s_35th__Archer <- readRDS(file = "rdata/35th__Archer.rds")
s_Addison___North_Main <- readRDS(file = "rdata/Addison-North_Main.rds")
s_Main <- readRDS(file = "rdata/Main.rds")
s_Chicago__State <- readRDS(file = "rdata/Chicago__State.rds")
s_Wellington <- readRDS(file = "rdata/Wellington.rds")
s_Austin___Forest_Park <- readRDS(file = "rdata/Austin-Forest_Park.rds")
s_Clinton___Lake <- readRDS(file = "rdata/Clinton-Lake.rds")
s_East_63rd___Cottage_Grove <- readRDS(file = "rdata/East_63rd-Cottage_Grove.rds")
s_Grand__State <- readRDS(file = "rdata/Grand__State.rds")
s_Wilson <- readRDS(file = "rdata/Wilson.rds")
s_Cicero___Cermak <- readRDS(file = "rdata/Cicero-Cermak.rds")
s_State__Lake <- readRDS(file = "rdata/State__Lake.rds")
s_51st <- readRDS(file = "rdata/51st.rds")
s_95th__Dan_Ryan <- readRDS(file = "rdata/95th__Dan_Ryan.rds")
s_Jackson__State <- readRDS(file = "rdata/Jackson__State.rds")
s_Randolph__Wabash <- readRDS(file = "rdata/Randolph__Wabash.rds")
s_Logan_Square <- readRDS(file = "rdata/Logan_Square.rds")
s_Morse <- readRDS(file = "rdata/Morse.rds")
s_Grand__Milwaukee <- readRDS(file = "rdata/Grand__Milwaukee.rds")
s_69th <- readRDS(file = "rdata/69th.rds")
s_Paulina <- readRDS(file = "rdata/Paulina.rds")
s_Damen___Brown <- readRDS(file = "rdata/Damen-Brown.rds")
s_Washington__Dearborn <- readRDS(file = "rdata/Washington__Dearborn.rds")
s_Kimball <- readRDS(file = "rdata/Kimball.rds")
s_Clark__Lake <- readRDS(file = "rdata/Clark__Lake.rds")
s_Lawrence <- readRDS(file = "rdata/Lawrence.rds")
s_Polk <- readRDS(file = "rdata/Polk.rds")
s_47th___Dan_Ryan <- readRDS(file = "rdata/47th-Dan_Ryan.rds")
s_Sedgwick <- readRDS(file = "rdata/Sedgwick.rds")
s_54th__Cermak <- readRDS(file = "rdata/54th__Cermak.rds")
s_Ashland__63rd <- readRDS(file = "rdata/Ashland__63rd.rds")
s_Morgan___Lake <- readRDS(file = "rdata/Morgan-Lake.rds")
s_Harrison <- readRDS(file = "rdata/Harrison.rds")
s_Sheridan <- readRDS(file = "rdata/Sheridan.rds")
s_Racine <- readRDS(file = "rdata/Racine.rds")
s_Washington__Wells <- readRDS(file = "rdata/Washington__Wells.rds")
s_Quincy__Wells <- readRDS(file = "rdata/Quincy__Wells.rds")
s_Foster <- readRDS(file = "rdata/Foster.rds")
s_California__Milwaukee <- readRDS(file = "rdata/California__Milwaukee.rds")
s_Cermak___McCormick_Place <- readRDS(file = "rdata/Cermak-McCormick_Place.rds")
s_Sox___35th___Dan_Ryan <- readRDS(file = "rdata/Sox-35th-Dan_Ryan.rds")
s_Chicago__Milwaukee <- readRDS(file = "rdata/Chicago__Milwaukee.rds")
s_OHare_Airport <- readRDS(file = "rdata/O'Hare_Airport.rds")
s_Kedzie___Lake <- readRDS(file = "rdata/Kedzie-Lake.rds")
s_Fullerton <- readRDS(file = "rdata/Fullerton.rds")
s_Irving_Park___Brown <- readRDS(file = "rdata/Irving_Park-Brown.rds")
s_LaSalle__Van_Buren <- readRDS(file = "rdata/LaSalle__Van_Buren.rds")
s_Belmont___North_Main <- readRDS(file = "rdata/Belmont-North_Main.rds")
s_79th <- readRDS(file = "rdata/79th.rds")
s_Adams__Wabash <- readRDS(file = "rdata/Adams__Wabash.rds")
s_Western___Orange <- readRDS(file = "rdata/Western-Orange.rds")
s_Clinton___Forest_Park <- readRDS(file = "rdata/Clinton-Forest_Park.rds")
s_UIC___Halsted <- readRDS(file = "rdata/UIC-Halsted.rds")
s_35___Bronzeville___IIT <- readRDS(file = "rdata/35-Bronzeville-IIT.rds")
s_87th <- readRDS(file = "rdata/87th.rds")
s_18th <- readRDS(file = "rdata/18th.rds")
s_Indiana <- readRDS(file = "rdata/Indiana.rds")
s_Monroe__State <- readRDS(file = "rdata/Monroe__State.rds")
s_Irving_Park___OHare <- readRDS(file = "rdata/Irving_Park-O'Hare.rds")
s_Cumberland <- readRDS(file = "rdata/Cumberland.rds")
s_Roosevelt <- readRDS(file = "rdata/Roosevelt.rds")
s_Damen__Milwaukee <- readRDS(file = "rdata/Damen__Milwaukee.rds")
s_Kedzie___Midway <- readRDS(file = "rdata/Kedzie-Midway.rds")
s_63rd___Dan_Ryan <- readRDS(file = "rdata/63rd-Dan_Ryan.rds")
s_Kedzie___Cermak <- readRDS(file = "rdata/Kedzie-Cermak.rds")
s_Addison___Brown <- readRDS(file = "rdata/Addison-Brown.rds")
s_Division__Milwaukee <- readRDS(file = "rdata/Division__Milwaukee.rds")
s_Damen___Cermak <- readRDS(file = "rdata/Damen-Cermak.rds")
s_Cicero___Lake <- readRDS(file = "rdata/Cicero-Lake.rds")
s_Madison__Wabash <- readRDS(file = "rdata/Madison__Wabash.rds")
s_Harlem___Lake <- readRDS(file = "rdata/Harlem-Lake.rds")
s_Pulaski___Cermak <- readRDS(file = "rdata/Pulaski-Cermak.rds")
s_Kedzie___Brown <- readRDS(file = "rdata/Kedzie-Brown.rds")
s_Central_Park <- readRDS(file = "rdata/Central_Park.rds")
s_Harlem___OHare <- readRDS(file = "rdata/Harlem-O'Hare.rds")
s_Chicago__Franklin <- readRDS(file = "rdata/Chicago__Franklin.rds")
s_North__Clybourn <- readRDS(file = "rdata/North__Clybourn.rds")
s_Berwyn <- readRDS(file = "rdata/Berwyn.rds")
s_Laramie <- readRDS(file = "rdata/Laramie.rds")
s_Howard <- readRDS(file = "rdata/Howard.rds")
s_Granville <- readRDS(file = "rdata/Granville.rds")
s_Western___Forest_Park <- readRDS(file = "rdata/Western-Forest_Park.rds")
s_California___Cermak <- readRDS(file = "rdata/California-Cermak.rds")
s_Ridgeland <- readRDS(file = "rdata/Ridgeland.rds")
s_Western___Cermak <- readRDS(file = "rdata/Western-Cermak.rds")
s_Halsted__63rd <- readRDS(file = "rdata/Halsted__63rd.rds")
s_Pulaski___Forest_Park <- readRDS(file = "rdata/Pulaski-Forest_Park.rds")
s_Montrose___Brown <- readRDS(file = "rdata/Montrose-Brown.rds")
s_Linden <- readRDS(file = "rdata/Linden.rds")
s_Pulaski___Lake <- readRDS(file = "rdata/Pulaski-Lake.rds")
s_Harlem___Forest_Park <- readRDS(file = "rdata/Harlem-Forest_Park.rds")
s_Ashland___Orange <- readRDS(file = "rdata/Ashland-Orange.rds")
s_Garfield___Dan_Ryan <- readRDS(file = "rdata/Garfield-Dan_Ryan.rds")
s_Halsted___Orange <- readRDS(file = "rdata/Halsted-Orange.rds")
s_Addison___OHare <- readRDS(file = "rdata/Addison-O'Hare.rds")
s_Pulaski___Orange <- readRDS(file = "rdata/Pulaski-Orange.rds")
s_Noyes <- readRDS(file = "rdata/Noyes.rds")
s_47th___South_Elevated <- readRDS(file = "rdata/47th-South_Elevated.rds")
s_Merchandise_Mart <- readRDS(file = "rdata/Merchandise_Mart.rds")
s_Midway_Airport <- readRDS(file = "rdata/Midway_Airport.rds")
s_43rd <- readRDS(file = "rdata/43rd.rds")
s_Western__Milwaukee <- readRDS(file = "rdata/Western__Milwaukee.rds")
s_Ashland___Lake <- readRDS(file = "rdata/Ashland-Lake.rds")
s_Belmont___OHare <- readRDS(file = "rdata/Belmont-O'Hare.rds")
s_Oak_Park___Lake <- readRDS(file = "rdata/Oak_Park-Lake.rds")
s_Conservatory <- readRDS(file = "rdata/Conservatory.rds")
s_Library <- readRDS(file = "rdata/Library.rds")
s_Loyola <- readRDS(file = "rdata/Loyola.rds")
s_Southport <- readRDS(file = "rdata/Southport.rds")
s_Montrose___OHare <- readRDS(file = "rdata/Montrose-O'Hare.rds")
s_Jarvis <- readRDS(file = "rdata/Jarvis.rds")
s_South_Boulevard <- readRDS(file = "rdata/South_Boulevard.rds")
s_Cicero___Forest_Park <- readRDS(file = "rdata/Cicero-Forest_Park.rds")
s_Medical_Center <- readRDS(file = "rdata/Medical_Center.rds")
s_Davis <- readRDS(file = "rdata/Davis.rds")
s_Clark__Division <- readRDS(file = "rdata/Clark__Division.rds")
s_Jackson__Dearborn <- readRDS(file = "rdata/Jackson__Dearborn.rds")
s_Washington__Wabash <- readRDS(file = "rdata/Washington__Wabash.rds")
s_Francisco <- readRDS(file = "rdata/Francisco.rds")
s_Central___Evanston <- readRDS(file = "rdata/Central-Evanston.rds")
s_Oakton___Skokie <- readRDS(file = "rdata/Oakton-Skokie.rds")
s_Austin___Lake <- readRDS(file = "rdata/Austin-Lake.rds")
s_Bryn_Mawr <- readRDS(file = "rdata/Bryn_Mawr.rds")
s_Kostner <- readRDS(file = "rdata/Kostner.rds")
s_Forest_Park <- readRDS(file = "rdata/Forest_Park.rds")
s_California___Lake <- readRDS(file = "rdata/California-Lake.rds")
s_Garfield___South_Elevated <- readRDS(file = "rdata/Garfield-South_Elevated.rds")
s_Rockwell <- readRDS(file = "rdata/Rockwell.rds")
s_Diversey <- readRDS(file = "rdata/Diversey.rds")
s_Argyle <- readRDS(file = "rdata/Argyle.rds")
s_LaSalle <- readRDS(file = "rdata/LaSalle.rds")
s_Monroe__Dearborn <- readRDS(file = "rdata/Monroe__Dearborn.rds")
s_Rosemont <- readRDS(file = "rdata/Rosemont.rds")
s_King_Drive <- readRDS(file = "rdata/King_Drive.rds")
s_Armitage <- readRDS(file = "rdata/Armitage.rds")
s_Thorndale <- readRDS(file = "rdata/Thorndale.rds")
s_Western___Brown <- readRDS(file = "rdata/Western-Brown.rds")
s_Skokie <- readRDS(file = "rdata/Skokie.rds")
s_Washington__State <- readRDS(file = "rdata/Washington__State.rds")
s_Homan <- readRDS(file = "rdata/Homan.rds")
allstationdf <-list(s_Jefferson_Park,s_Cermak___Chinatown,s_Central___Lake,s_Dempster___Skokie,s_Dempster,s_Lake__State,s_Oak_Park___Forest_Park,s_Kedzie___Homan___Forest_Park,s_35th__Archer,s_Addison___North_Main,s_Main,s_Chicago__State,s_Wellington,s_Austin___Forest_Park,s_Clinton___Lake,s_East_63rd___Cottage_Grove,s_Grand__State,s_Wilson,s_Cicero___Cermak,s_State__Lake,s_51st,s_95th__Dan_Ryan,s_Jackson__State,s_Randolph__Wabash,s_Logan_Square,s_Morse,s_Grand__Milwaukee,s_69th,s_Paulina,s_Damen___Brown,s_Washington__Dearborn,s_Kimball,s_Clark__Lake,s_Lawrence,s_Polk,s_47th___Dan_Ryan,s_Sedgwick,s_54th__Cermak,s_Ashland__63rd,s_Morgan___Lake,s_Harrison,s_Sheridan,s_Racine,s_Washington__Wells,s_Quincy__Wells,s_Foster,s_California__Milwaukee,s_Cermak___McCormick_Place,s_Sox___35th___Dan_Ryan,s_Chicago__Milwaukee,s_OHare_Airport,s_Kedzie___Lake,s_Fullerton,s_Irving_Park___Brown,s_LaSalle__Van_Buren,s_Belmont___North_Main,s_79th,s_Adams__Wabash,s_Western___Orange,s_Clinton___Forest_Park,s_UIC___Halsted,s_35___Bronzeville___IIT,s_87th,s_18th,s_Indiana,s_Monroe__State,s_Irving_Park___OHare,s_Cumberland,s_Roosevelt,s_Damen__Milwaukee,s_Kedzie___Midway,s_63rd___Dan_Ryan,s_Kedzie___Cermak,s_Addison___Brown,s_Division__Milwaukee,s_Damen___Cermak,s_Cicero___Lake,s_Madison__Wabash,s_Harlem___Lake,s_Pulaski___Cermak,s_Kedzie___Brown,s_Central_Park,s_Harlem___OHare,s_Chicago__Franklin,s_North__Clybourn,s_Berwyn,s_Laramie,s_Howard,s_Granville,s_Western___Forest_Park,s_California___Cermak,s_Ridgeland,s_Western___Cermak,s_Halsted__63rd,s_Pulaski___Forest_Park,s_Montrose___Brown,s_Linden,s_Pulaski___Lake,s_Harlem___Forest_Park,s_Ashland___Orange,s_Garfield___Dan_Ryan,s_Halsted___Orange,s_Addison___OHare,s_Pulaski___Orange,s_Noyes,s_47th___South_Elevated,s_Merchandise_Mart,s_Midway_Airport,s_43rd,s_Western__Milwaukee,s_Ashland___Lake,s_Belmont___OHare,s_Oak_Park___Lake,s_Conservatory,s_Library,s_Loyola,s_Southport,s_Montrose___OHare,s_Jarvis,s_South_Boulevard,s_Cicero___Forest_Park,s_Medical_Center,s_Davis,s_Clark__Division,s_Jackson__Dearborn,s_Washington__Wabash,s_Francisco,s_Central___Evanston,s_Oakton___Skokie,s_Austin___Lake,s_Bryn_Mawr,s_Kostner,s_Forest_Park,s_California___Lake,s_Garfield___South_Elevated,s_Rockwell,s_Diversey,s_Argyle,s_LaSalle,s_Monroe__Dearborn,s_Rosemont,s_King_Drive,s_Armitage,s_Thorndale,s_Western___Brown,s_Skokie,s_Washington__State,s_Homan)
dfMerge <- do.call("rbind", allstationdf)
dfMerge <- dfMerge[order(dfMerge$stationname),]

latlonstation <- read.csv(file = 'data/lonlat.csv')
for(sdf in allstationdf)
{
  sdf
}
sdf$stationname[1]
